'use strict';

exports.BattlePokedex = {
	bittercold: {
		num: -339,
		species: "Cryogonal",
		types: ["Ice"],
		genderRatio: "N",
		baseStats: {hp: 115, atk: 45, def: 100, spa: 45, spd: 100, spe: 20},
		abilities: {0: "Color Change"},
		heightm: 73.5,
		weightkg: 246.5,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	shinx: {
		num: 403,
		species: "Shinx",
		types: ["Electric"],
		baseStats: {hp: 155, atk: 65, def: 34, spa: 40, spd: 34, spe: 45},
		abilities: {0: "Rivalry", 1: "Intimidate", H: "Guts"},
		heightm: 0.5,
		weightkg: 9.5,
		color: "Blue",
		evos: ["luxio"],
		eggGroups: ["Field"],
	},
	munchlax: {
		num: 446,
		species: "Munchlax",
		types: ["Normal"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 155, atk: 85, def: 40, spa: 40, spd: 85, spe: 5},
		abilities: {0: "Pickup", 1: "Thick Fat", H: "Gluttony"},
		heightm: 0.6,
		weightkg: 105,
		color: "Black",
		evos: ["snorlax"],
		eggGroups: ["Undiscovered"],
	},
};
