'use strict';

exports.BattlePokedex = {
	rinocaw: {
		num: 1000,
		species: "Rinocaw",
		types: ["Ground"],
		baseStats: {hp: 85, atk: 70, def: 80, spa: 30, spd: 45, spe: 40},
		abilities: {0: "Arena Trap", H: "Reckless"},
		heightm: 0.35,
		weightkg: 24.3,
		color: "Brown",
		eggGroups: ["Mineral"],
		evos: ["rinocoss"],
	},
	rinocoss: {
		num: 1001,
		species: "Rinocoss",
		types: ["Fighting", "Ground"],
		baseStats: {hp: 105, atk: 100, def: 100, spa: 60, spd: 65, spe: 80},
		abilities: {0: "Arena Trap", H: "Reckless"},
		heightm: 1.4,
		weightkg: 291.8,
		color: "Brown",
		eggGroups: ["Mineral", "Monster"],
		prevo: "rinocaw",
		otherFormes: ["Rinocoss-Mega"],
	},
	rinocossmega: {
		num: 1002,
		species: "Rinocoss-Mega",
		baseSpecies: "Rinocoss",
		types: ["Steel", "Ground"],
		formeLetter: "M",
		forme: "Mega",
		baseStats: {hp: 105, atk: 115, def: 125, spa: 80, spd: 90, spe: 95},
		abilities: {0: "Arena Trap"},
		heightm: 1.5,
		weightkg: 193,
		color: "Brown",
		eggGroups: ["Mineral", "Monster"],
	},
	mariamyte: {
		num: 1003,
		species: "Mariamyte",
		types: ["Ghost", "Normal"],
		baseStats: {hp: 30, atk: 45, def: 40, spa: 45, spd: 65, spe: 90},
		abilities: {0: "Cursed Body", H: "Color Change"},
		heightm: 0.6,
		weightkg: 0.1,
		color: "Black",
		eggGroups: ["Undiscovered"],
		evos: ["Marionyte"],
	},
	marionyte: {
		num: 1004,
		species: "Marionyte",
		types: ["Ghost", "Normal"],
		baseStats: {hp: 60, atk: 85, def: 70, spa: 85, spd: 95, spe: 125},
		abilities: {0: "Cursed Body", H: "Color Change"},
		heightm: 2,
		weightkg: 0.4,
		color: "Black",
		eggGroups: ["Undiscovered"],
		prevo: "Mariamyte",
		otherFormes: ["Marionyte-Mega"],
	},
	marionytemega: {
		num: 1005,
		species: "Marionyte-Mega",
		baseSpecies: "Marionyte",
		formeLetter: "M",
		forme: "Mega",
		types: ["Ghost", "Normal"],
		baseStats: {hp: 60, atk: 105, def: 85, spa: 120, spd: 100, spe: 150},
		abilities: {0: "Shadow Tag"},
		heightm: 2.5,
		weightkg: 0.5,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
};