"use strict";

const RandomTeams = require("../../data/random-teams");

class RandomCOTRTeams extends RandomTeams {
	randomCOTRTeam() {
		let team = [];
		let sets = {
			//gen1
			"Brock": {
				species: "Onix",
				ability: "Sturdy",
				item: "Weakness Policy",
				gender: "M",
				moves: ["Flail", "Rock Polish", "Stone Edge"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Ash": {
				species: "Pikachu",
				ability: "Static",
				item: "Light Ball",
				gender: "M",
				moves: ["Volt Tackle", "Iron Tail", "Fake Out"],
				signatureMove: "Extreme Speed",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Misty": {
				species: "Starmie",
				ability: "Natural Cure",
				item: "Life Orb",
				gender: "F",
				moves: ["Hydro Pump", "Ice Beam", "Thunderbolt"],
				signatureMove: "Psyshock",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Koga": {
				species: "Weezing",
				ability: "Levitate",
				item: "Black Sludge",
				gender: "M",
				moves: ["Toxic Spikes", "Pain Split", "Sludge Bomb"],
				signatureMove: "Explosion",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Relaxed",
			},
			"Lt. Surge": {
				species: "Raichu",
				ability: "Lightning Rod",
				item: "Life Orb",
				gender: "M",
				moves: ["Thunderbolt", "Focus Blast", "Volt Switch"],
				signatureMove: "Hidden Power Ice",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Blaine": {
				species: "Arcanine",
				ability: "Intimidate",
				item: "Leftovers",
				gender: "M",
				moves: ["Flare Blitz", "Wild Charge", "Morning Sun"],
				signatureMove: "Extreme Speed",
				evs: {
					atk: 4,
					hp: 252,
					def: 252,
				},
				nature: "Impish",
			},
			"Sabrina": {
				species: "Alakazam",
				ability: "Magic Guard",
				item: "Focus Sash",
				gender: "F",
				moves: ["Focus Blast", "Dazzling Gleam", "Shadow Ball"],
				signatureMove: "Psychic",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Erika": {
				species: "Vileplume",
				ability: "Effect Spore",
				item: "Black Sludge",
				gender: "F",
				moves: ["Giga Drain", "Toxic", "Teeter Dance"],
				signatureMove: "Synthesis",
				evs: {
					hp: 252,
					spd: 252,
					spa: 4,
				},
				nature: "Calm",
			},
			"Giovanni": {
				species: "Nidoking",
				ability: "Sheer Force",
				item: "Life Orb",
				gender: "M",
				moves: ["Sludge Wave", "Thunderbolt", "Ice Beam"],
				signatureMove: "Earth Power",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Lorelei": {
				species: "Lapras",
				ability: "Water Absorb",
				item: "Leftovers",
				gender: "F",
				moves: ["Scald", "Freeze-Dry", "Rest"],
				signatureMove: "Sleep Talk",
				evs: {
					spa: 252,
					hp: 252,
					def: 4,
				},
				nature: "Modest",
			},
			"Bruno": {
				species: "Machamp",
				ability: "No Guard",
				item: "Life Orb",
				gender: "M",
				moves: ["Dynamic Punch", "Bullet Punch", "Knock Off"],
				signatureMove: "Stone Edge",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Agatha": {
				species: "Gengar",
				ability: "Cursed Body",
				item: "Focus Sash",
				gender: "F",
				moves: ["Shadow Ball", "Sludge Wave", "Dazzling Gleam"],
				signatureMove: "Destiny Bond",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Lance": {
				species: "Dragonite",
				ability: "Multiscale",
				item: "Lum Berry",
				gender: "M",
				moves: ["Outrage", "Earthquake", "Extreme Speed"],
				signatureMove: "Dragon Dance",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Blue": {
				species: "Blastoise",
				ability: "Rain Dish",
				item: "Assault Vest",
				gender: "M",
				moves: ["Scald", "Ice Beam", "Flash Cannon"],
				signatureMove: "Aura Sphere",
				evs: {
					spa: 252,
					hp: 252,
					spd: 4,
				},
				nature: "Modest",
			},
			"Red": {
				species: "Charizard",
				ability: "Blaze",
				item: "Charizardite-X",
				gender: "M",
				moves: ["Fire Punch", "Belly Drum", "Roost"],
				signatureMove: "Dragon Claw",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Green": {
				species: "Venusaur",
				ability: "Overgrow",
				item: "Black Sludge",
				gender: "M",
				moves: ["Giga Drain", "Synthesis", "Toxic"],
				signatureMove: "Knock Off",
				evs: {
					hp: 252,
					spd: 252,
					spa: 4,
				},
				nature: "Calm",
			},
			"Team Rocket": {
				species: "Persian",
				ability: "Technician",
				item: "Life Orb",
				gender: "M",
				moves: ["Fake Out", "Return", "U-Turn"],
				signatureMove: "Knock Off",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			//gen2
			"Falkner": {
				species: "Pidgeot",
				ability: "Big Pecks",
				item: "Life Orb",
				gender: "M",
				moves: ["Brave Bird", "Return", "U-Turn"],
				signatureMove: "Defog",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Bugsy": {
				species: "Scyther",
				ability: "Technician",
				item: "Eviolite",
				gender: "M",
				moves: ["Swords Dance", "Roost", "Aerial Ace"],
				signatureMove: "Bug Bite",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Whitney": {
				species: "Miltank",
				ability: "Thick Fat",
				item: "Leftovers",
				gender: "F",
				moves: ["Seismic Toss", "Curse", "Toxic"],
				signatureMove: "Milk Drink",
				evs: {
					hp: 252,
					spd: 252,
					def: 4,
				},
				nature: "Careful",
			},
			"Morty": {
				species: "Gengar",
				ability: "Cursed Body",
				item: "Life Orb",
				gender: "M",
				moves: ["Sludge Wave", "Dazzling Gleam", "Psychic"],
				signatureMove: "Shadow Ball",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Janine": {
				species: "Venomoth",
				ability: "Tinted Lens",
				item: "Leftovers",
				gender: "F",
				moves: ["Bug Buzz", "Sludge Bomb", "Giga Drain"],
				signatureMove: "Quiver Dance",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Chuck": {
				species: "Poliwrath",
				ability: "Water Absorb",
				item: "Life Orb",
				gender: "M",
				moves: ["Waterfall", "Belly Drum", "Ice Punch"],
				signatureMove: "Brick Break",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Jasmine": {
				species: "Steelix",
				ability: "Sheer Force",
				item: "Leftovers",
				gender: "F",
				moves: ["Rock Slide", "Earthquake", "Stealth Rock"],
				signatureMove: "Iron Head",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Pryce": {
				species: "Mamoswine",
				ability: "Thick Fat",
				item: "Life Orb",
				gender: "M",
				moves: ["Icicle Crash", "Knock Off", "Ice Shard"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Adamant",
			},
			"Clair": {
				species: "Kingdra",
				ability: "Sniper",
				item: "Scope Lens",
				gender: "F",
				moves: ["Scald", "Draco Meteor", "Focus Energy"],
				signatureMove: "Ice Beam",
				evs: {
					spa: 252,
					hp: 252,
					def: 4,
				},
				nature: "Modest",
			},
			"Will": {
				species: "Xatu",
				ability: "Magic Bounce",
				item: "Light Clay",
				gender: "M",
				moves: ["Psyshock", "Air Slash", "Reflect"],
				signatureMove: "Light Screen",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Karen": {
				species: "Houndoom",
				ability: "Flash Fire",
				item: "Life Orb",
				gender: "F",
				moves: ["Flamethrower", "Energy Ball", "Sucker Punch"],
				signatureMove: "Dark Pulse",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Naive",
			},
			//gen3
			"Brawly": {
				species: "Hariyama",
				ability: "Thick Fat",
				item: "Assault Vest",
				gender: "M",
				moves: ["Close Combat", "Knock Off", "Earthquake"],
				signatureMove: "Bullet Punch",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Liza": {
				species: "Lunatone",
				ability: "Levitate",
				item: "Choice Specs",
				gender: "F",
				moves: ["Earth Power", "Ice Beam", "Moonblast"],
				signatureMove: "Psychic",
				evs: {
					spa: 252,
					hp: 252,
					def: 4,
				},
				nature: "Modest",
			},
			"Tate": {
				species: "Solrock",
				ability: "Levitate",
				item: "Leftovers",
				gender: "M",
				moves: ["Will-O-Wisp", "Morning Sun", "Rock Slide"],
				signatureMove: "Zen Headbutt",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Impish",
			},
			"Winona": {
				species: "Altaria",
				ability: "Natural Cure",
				item: "Leftovers",
				gender: "F",
				moves: ["Heal Bell", "Roost", "Cotton Guard"],
				signatureMove: "Dragon Pulse",
				evs: {
					hp: 252,
					spd: 252,
					def: 4,
				},
				nature: "Calm",
			},
			"Roxanne": {
				species: "Probopass",
				ability: "Sturdy",
				item: "Leftovers",
				gender: "F",
				moves: ["Power Gem", "Pain Split", "Toxic"],
				signatureMove: "Stealth Rock",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Relaxed",
			},
			"Wattson": {
				species: "Magneton",
				ability: "Analytic",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Thunderbolt", "Hidden Power Fire", "Flash Cannon"],
				signatureMove: "Volt Switch",
				evs: {
					spa: 252,
					spe: 252,
					def: 4,
				},
				nature: "Timid",
			},
			"Flannery": {
				species: "Torkoal",
				ability: "Drought",
				item: "White Herb",
				gender: "F",
				moves: ["Flamethrower", "Earth Power", "Sludge Wave"],
				signatureMove: "Shell Smash",
				evs: {
					spa: 252,
					hp: 252,
					def: 4,
				},
				nature: "Modest",
			},
			"Norman": {
				species: "Slaking",
				ability: "Truant",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Giga Impact", "Night Slash", "Ice Punch"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Wallace": {
				species: "Milotic",
				ability: "Marvel Scale",
				item: "Flame Orb",
				gender: "M",
				moves: ["Scald", "Dragon Tail", "Recover"],
				signatureMove: "Toxic",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Bold",
			},
			"Sidney": {
				species: "Absol",
				ability: "Super Luck",
				item: "Absolite",
				gender: "M",
				moves: ["Swords Dance", "Psycho Cut", "Knock Off"],
				signatureMove: "Sucker Punch",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Phoebe": {
				species: "Sableye",
				ability: "Prankster",
				item: "Sablenite",
				gender: "F",
				moves: ["Will-O-Wisp", "darkpulse", "recover"],
				signatureMove: "Calm Mind",
				evs: {
					hp: 252,
					spd: 252,
					spa: 4,
				},
				nature: "Calm",
			},
			"Glacia": {
				species: "Glalie",
				ability: "Ice Body",
				item: "Glalitite",
				gender: "F",
				moves: ["Return", "Ice Shard", "Earthquake"],
				signatureMove: "Explosion",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Drake": {
				species: "Salamence",
				ability: "Intimidate",
				item: "Salamencite",
				gender: "M",
				moves: ["Return", "Roost", "Dragon Dance"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Steven": {
				species: "Metagross",
				ability: "Clear Body",
				item: "Metagrossite",
				gender: "M",
				moves: ["meteormash", "zenheadbutt", "Earthquake"],
				signatureMove: "Bullet Punch",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Wally": {
				species: "Gallade",
				ability: "Justified",
				item: "Galladite",
				gender: "M",
				moves: ["Close Combat", "Psycho Cut", "Swords Dance"],
				signatureMove: "Knock Off",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Juan": {
				species: "Kingdra",
				ability: "Sniper",
				item: "Scope Lens",
				gender: "M",
				moves: ["Outrage", "Waterfall", "Iron Head"],
				signatureMove: "Focus Energy",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Team Magma": {
				species: "Camerupt",
				ability: "Solid Rock",
				item: "Cameruptite",
				gender: "M",
				moves: ["Flamethrower", "Earth Power", "Rock Polish"],
				signatureMove: "Flash Cannon",
				evs: {
					spa: 252,
					spe: 252,
					def: 4,
				},
				nature: "Timid",
			},
			"Team Aqua": {
				species: "Sharpedo",
				ability: "Speed Boost",
				item: "Sharpedonite",
				gender: "M",
				moves: ["Waterfall", "Crunch", "Protect"],
				signatureMove: "Ice Fang",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			//gen4
			"Roark": {
				species: "Rampardos",
				ability: "Sheer Force",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Head Smash", "Earthquake", "Iron Head"],
				signatureMove: "Zen Headbutt",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Gardenia": {
				species: "Roserade",
				ability: "Technician",
				item: "Life Orb",
				gender: "M",
				moves: ["Giga Drain", "Sludge Bomb", "Hidden Power Fire"],
				signatureMove: "Dazzling Gleam",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Maylene": {
				species: "Lucario",
				ability: "Justified",
				item: "Life Orb",
				gender: "M",
				moves: ["Close Combat", "Bullet Punch", "Extreme Speed"],
				signatureMove: "Ice Punch",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Crasher Wake": {
				species: "Floatzel",
				ability: "Water Veil",
				item: "Leftovers",
				gender: "M",
				moves: ["Waterfall", "Ice Punch", "Bulk Up"],
				signatureMove: "Aqua Jet",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Fantina": {
				species: "Mismagius",
				ability: "Levitate",
				item: "Life Orb",
				gender: "F",
				moves: ["Shadow Ball", "Dazzling Gleam", "Sucker Punch"],
				signatureMove: "Nasty Plot",
				evs: {
					spa: 252,
					spe: 252,
					atk: 4,
				},
				nature: "Hasty",
			},
			"Byron": {
				species: "Bastiodon",
				ability: "Sturdy",
				item: "Air Balloon",
				gender: "M",
				moves: ["Iron Head", "Rock Slide", "Earthquake"],
				signatureMove: "Stealth Rock",
				evs: {
					hp: 252,
					spd: 252,
					def: 4,
				},
				nature: "Careful",
			},
			"Candice": {
				species: "Froslass",
				ability: "Cursed Body",
				item: "Focus Sash",
				gender: "F",
				moves: ["Ice Beam", "Shadow Ball", "Thunder Wave"],
				signatureMove: "Destiny Bond",
				evs: {
					spa: 252,
					spe: 252,
					atk: 4,
				},
				nature: "Hasty",
			},
			"Volkner": {
				species: "Electivire",
				ability: "Vital Spirit",
				item: "Choice Band",
				gender: "M",
				moves: ["Ice Punch", "Earthquake", "Cross Chop"],
				signatureMove: "Wild Charge",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Aaron": {
				species: "Drapion",
				ability: "Battle Armor",
				item: "Assault Vest",
				gender: "M",
				moves: ["Poison Jab", "Knock Off", "Earthquake"],
				signatureMove: "Rock Slide",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Bertha": {
				species: "Hippowdon",
				ability: "Sand Stream",
				item: "Leftovers",
				gender: "F",
				moves: ["Earthquake", "Whirlwind", "Stealth Rock"],
				signatureMove: "Slack Off",
				evs: {
					hp: 252,
					def: 252,
					atk: 4,
				},
				nature: "Impish",
			},
			"Flint": {
				species: "Infernape",
				ability: "Iron Fist",
				item: "Life Orb",
				gender: "M",
				moves: ["Flare Blitz", "Close Combat", "U-Turn"],
				signatureMove: "Mach Punch",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Lucian": {
				species: "Bronzong",
				ability: "Levitate",
				item: "Light Clay",
				gender: "F",
				moves: ["Gyro Ball", "Reflect", "Light Screen"],
				signatureMove: "Stealth Rock",
				evs: {
					hp: 248,
					spd: 252,
					def: 8,
				},
				nature: "Sassy",
			},
			"Cynthia": {
				species: "Garchomp",
				ability: "Rough Skin",
				item: "Rocky Helmet",
				gender: "F",
				moves: ["Outrage", "Earthquake", "Swords Dance"],
				signatureMove: "Stealth Rock",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Team Galactic": {
				species: "Porygon-Z",
				ability: "Download",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Tri Attack", "Psychic", "Thunderbolt"],
				signatureMove: "Ice Beam",
				evs: {
					spa: 252,
					spe: 252,
					def: 4,
				},
				nature: "Timid",
			},
			//gen5
			"Cilan": {
				species: "Simisage",
				ability: "Overgrow",
				item: "Life Orb",
				gender: "M",
				moves: ["Leaf Storm", "Focus Blast", "Hidden Power Ice"],
				signatureMove: "Giga Drain",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Chili": {
				species: "Simisear",
				ability: "Blaze",
				item: "Life Orb",
				gender: "M",
				moves: ["Overheat", "Rock Slide", "Knock Off"],
				signatureMove: "Gunk Shot",
				evs: {
					atk: 252,
					spe: 252,
					spa: 4,
				},
				nature: "Hasty",
			},
			"Cress": {
				species: "Simipour",
				ability: "Torrent",
				item: "Life Orb",
				gender: "M",
				moves: ["Scald", "Knock Off", "Ice Beam"],
				signatureMove: "Grass Knot",
				evs: {
					spa: 252,
					spe: 252,
					atk: 4,
				},
				nature: "Hasty",
			},
			"Lenora": {
				species: "Watchog",
				ability: "Analytic",
				item: "Leftovers",
				gender: "F",
				moves: ["Return", "Knock Off", "Gunk Shot"],
				signatureMove: "Zen Headbutt",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Burgh": {
				species: "Leavanny",
				ability: "Swarm",
				item: "Focus Sash",
				gender: "M",
				moves: ["Fell Stinger", "Leaf Blade", "Knock Off"],
				signatureMove: "Sticky Web",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Elesa": {
				species: "Zebstrika",
				ability: "Motor Drive",
				item: "Life Orb",
				gender: "F",
				moves: ["Thunderbolt", "Overheat", "Hidden Power Ice"],
				signatureMove: "Volt Switch",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Clay": {
				species: "Excadrill",
				ability: "Mold Breaker",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Earthquake", "Iron Head", "X-Scissor"],
				signatureMove: "Rock Slide",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Skyla": {
				species: "Swanna",
				ability: "Hydration",
				item: "Life Orb",
				gender: "M",
				moves: ["Scald", "Air Slash", "Roost"],
				signatureMove: "Defog",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Brycen": {
				species: "Beartic",
				ability: "Swift Swim",
				item: "Life Orb",
				gender: "M",
				moves: ["Icicle Crash", "Play Rough", "Superpower"],
				signatureMove: "Aqua Jet",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Drayden": {
				species: "Haxorus",
				ability: "Mold Breaker",
				item: "Choice Band",
				gender: "M",
				moves: ["Outrage", "Earthquake", "Rock Slide"],
				signatureMove: "Poison Jab",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Iris": {
				species: "Haxorus",
				ability: "Rivalry",
				item: "Life Orb",
				gender: "F",
				moves: ["Dragon Claw", "Earthquake", "Rock Slide"],
				signatureMove: "Poison Jab",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Shauntal": {
				species: "Chandelure",
				ability: "Flash Fire",
				item: "Choice Scarf",
				gender: "F",
				moves: ["Shadow Ball", "Flamethrower", "Energy Ball"],
				signatureMove: "Psychic",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Grimsley": {
				species: "Bisharp",
				ability: "Defiant",
				item: "Focus Sash",
				gender: "M",
				moves: ["Iron Head", "Knock Off", "Swords Dance"],
				signatureMove: "Sucker Punch",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Caitlin": {
				species: "Gothitelle",
				ability: "Shadow Tag",
				item: "Choice Scarf",
				gender: "F",
				moves: ["Psyshock", "Trick", "Calm Mind"],
				signatureMove: "Rest",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Marshal": {
				species: "Mienshao",
				ability: "Reckless",
				item: "Life Orb",
				gender: "M",
				moves: ["Fake Out", "High Jump Kick", "Knock Off"],
				signatureMove: "U-Turn",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Alder": {
				species: "Volcarona",
				ability: "Swarm",
				item: "Leftovers",
				gender: "M",
				moves: ["Fiery Dance", "Bug Buzz", "Giga Drain"],
				signatureMove: "Quiver Dance",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Modest",
			},
			"Team Plasma": {
				species: "Liepard",
				ability: "Unburden",
				item: "Focus Sash",
				gender: "F",
				moves: ["Knock Off", "Sucker Punch", "Play Rough"],
				signatureMove: "Gunk Shot",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			//gen6
			"Lysandre": {
				species: "Gyarados",
				ability: "Intimidate",
				item: "Gyaradosite",
				gender: "M",
				moves: ["Waterfall", "Earthquake", "Crunch"],
				signatureMove: "Dragon Dance",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Viola": {
				species: "Vivillon",
				ability: "Compound Eyes",
				item: "Focus Sash",
				gender: "F",
				moves: ["Bug Buzz", "Hurricane", "Sleep Powder"],
				signatureMove: "Quiver Dance",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Grant": {
				species: "Tyrantrum",
				ability: "Rock Head",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Earthquake", "Superpower", "Ice Fang"],
				signatureMove: "Head Smash",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Korrina": {
				species: "Hawlucha",
				ability: "Unburden",
				item: "Sitrus Berry",
				gender: "F",
				moves: ["Zen Headbutt", "Stone Edge", "Swords Dance"],
				signatureMove: "Flying Press",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Ramos": {
				species: "Gogoat",
				ability: "Sap Sipper",
				item: "Leftovers",
				gender: "M",
				moves: ["Milk Drink", "Bulk Up", "Earthquake"],
				signatureMove: "Horn Leech",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Clemont": {
				species: "Heliolisk",
				ability: "Dry Skin",
				item: "Life Orb",
				gender: "M",
				moves: ["Thunderbolt", "Hyper Voice", "Surf"],
				signatureMove: "Focus Blast",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Valerie": {
				species: "Sylveon",
				ability: "Pixilate",
				item: "Leftovers",
				gender: "F",
				moves: ["Hyper Voice", "Wish", "Protect"],
				signatureMove: "Calm Mind",
				evs: {
					def: 252,
					hp: 252,
					spa: 4,
				},
				nature: "Bold",
			},
			"Olympia": {
				species: "Meowstic",
				ability: "Competitive",
				item: "Life Orb",
				gender: "F",
				moves: ["Fake Out", "Sucker Punch", "Thunderbolt"],
				signatureMove: "Psychic",
				evs: {
					spa: 252,
					spe: 252,
					atk: 4,
				},
				nature: "Hasty",
			},
			"Wulfric": {
				species: "Avalugg",
				ability: "Sturdy",
				item: "Leftovers",
				gender: "M",
				moves: ["Avalanche", "Earthquake", "Curse"],
				signatureMove: "Recover",
				evs: {
					hp: 252,
					def: 252,
					atk: 4,
				},
				nature: "Relaxed",
			},
			"Wilkstrom": {
				species: "Aegislash",
				ability: "Stance Change",
				item: "Weakness Policy",
				gender: "M",
				moves: ["Iron Head", "Shadow Sneak", "Sacred Sword"],
				signatureMove: "King's Shield",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Malva": {
				species: "Talonflame",
				ability: "Gale Wings",
				item: "Leftovers",
				gender: "F",
				moves: ["Brave Bird", "Taunt", "Roost"],
				signatureMove: "Bulk Up",
				evs: {
					hp: 252,
					spd: 252,
					def: 4,
				},
				nature: "Careful",
			},
			"Drasna": {
				species: "Noivern",
				ability: "Infiltrator",
				item: "Life Orb",
				gender: "F",
				moves: ["Draco Meteor", "Hurricane", "Flamethrower"],
				signatureMove: "Focus Blast",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Siebold": {
				species: "Barbaracle",
				ability: "Tough Claws",
				item: "White Herb",
				gender: "M",
				moves: ["Waterfall", "Stone Edge", "Earthquake"],
				signatureMove: "Shell Smash",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Diantha": {
				species: "Gardevoir",
				ability: "Trace",
				item: "Gardevoirite",
				gender: "F",
				moves: ["Psychic", "Hyper Voice", "Focus Blast"],
				signatureMove: "Thunderbolt",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Team Flare": {
				species: "Scrafty",
				ability: "Moxie",
				item: "Chople Berry",
				gender: "M",
				moves: ["Dragon Dance", "High Jump Kick", "Iron Head"],
				signatureMove: "Knock Off",
				evs: {
					atk: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Jolly",
			},
			//Random Stuff (there was some up there but oh well) Mainly Anime based/Rivals etc
			"May": {
				species: "Blaziken",
				ability: "Speed Boost",
				item: "Life Orb",
				gender: "F",
				moves: ["Knock Off", "High Jump Kick", "Protect"],
				signatureMove: "Flare Blitz",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Cameron": {
				species: "Lucario",
				ability: "Justified",
				item: "Life Orb",
				gender: "M",
				moves: ["Nasty Plot", "Vacuum Wave", "Flash Cannon"],
				signatureMove: "Aura Sphere",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Gary": {
				species: "Blastoise",
				ability: "Torrent",
				item: "Leftovers",
				gender: "M",
				moves: ["Scald", "Toxic", "Rapid Spin"],
				signatureMove: "Refresh",
				evs: {
					hp: 252,
					spd: 252,
					def: 4,
				},
				nature: "Bold",
			},
			"Bianca": {
				species: "Emboar",
				ability: "Reckless",
				item: "Life Orb",
				gender: "F",
				moves: ["Flare Blitz", "Sucker Punch", "Wild Charge"],
				signatureMove: "Head Smash",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Ash's Housekeeper": {
				species: "Mr. Mime",
				ability: "Filter",
				item: "Choice Scarf",
				gender: "F",
				moves: ["Psychic", "Thunderbolt", "Dazzling Gleam"],
				signatureMove: "Shadow Ball",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Serena": {
				species: "Delphox",
				ability: "Magician",
				item: "Power Herb",
				gender: "F",
				moves: ["Flamethrower", "Solar Beam", "Grass Knot"],
				signatureMove: "Psychic",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Nurse Joy": {
				species: "Chansey",
				ability: "Natural Cure",
				item: "Eviolite",
				gender: "F",
				moves: ["Seismic Toss", "Toxic", "Heal Bell"],
				signatureMove: "Soft-Boiled",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Bold",
			},
			"Officer Jenny": {
				species: "Arcanine",
				ability: "Intimidate",
				item: "Leftovers",
				gender: "F",
				moves: ["Flare Blitz", "Wild Charge", "Close Combat"],
				signatureMove: "Extreme Speed",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"James": {
				species: "Weezing",
				ability: "Levitate",
				item: "Black Sludge",
				gender: "M",
				moves: ["Sludge Bomb", "Destiny Bond", "Will-O-Wisp"],
				signatureMove: "Pain Split",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Bold",
			},
			"Jessie": {
				species: "Arbok",
				ability: "Shed Skin",
				item: "Black Sludge",
				gender: "F",
				moves: ["Poison Jab", "Sucker Punch", "Earthquake"],
				signatureMove: "Coil",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Dawn": {
				species: "Empoleon",
				ability: "Torrent",
				item: "Leftovers",
				gender: "F",
				moves: ["Defog", "Toxic", "Stealth Rock"],
				signatureMove: "Scald",
				evs: {
					hp: 252,
					def: 252,
					spa: 4,
				},
				nature: "Bold",
			},
			"Youngster Joey": {
				species: "Rattata",
				ability: "Guts",
				item: "Focus Sash",
				gender: "M",
				moves: ["Facade", "Endeavor", "Sucker Punch"],
				signatureMove: "Quick Attack",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Cheren": {
				species: "Stoutland",
				ability: "Scrappy",
				item: "Choice Band",
				gender: "M",
				moves: ["Crunch", "Play Rough", "Return"],
				signatureMove: "Superpower",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Adamant",
			},
			"Professor Oak": {
				species: "Dragonite",
				ability: "Multiscale",
				item: "Choice Band",
				gender: "M",
				moves: ["Earthquake", "Fire Punch", "Extreme Speed"],
				signatureMove: "Dragon Claw",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Zinnia": {
				species: "Exploud",
				ability: "Scrappy",
				item: "Choice Specs",
				gender: "F",
				moves: ["Boomburst", "Fire Blast", "Surf"],
				signatureMove: "Focus Blast",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Modest",
			},
			"N": {
				species: "Reshiram",
				ability: "Turboblaze",
				item: "Choice Specs",
				gender: "M",
				moves: ["Blue Flare", "Draco Meteor", "Earth Power"],
				signatureMove: "Hidden Power Ice",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Modest",
			},
			"Colress": {
				species: "Klinklang",
				ability: "Clear Body",
				item: "Leftovers",
				gender: "M",
				moves: ["Shift Gear", "Gear Grind", "Magnet Rise"],
				signatureMove: "Wild Charge",
				evs: {
					hp: 252,
					atk: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Ghetsis": {
				species: "Hydreigon",
				ability: "Levitate",
				item: "Choice Scarf",
				gender: "M",
				moves: ["Dark Pulse", "Draco Meteor", "Flash Cannon"],
				signatureMove: "Fire Blast",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"White": {
				species: "Serperior",
				ability: "Contrary",
				item: "Life Orb",
				gender: "F",
				moves: ["Leaf Storm", "Hidden Power Fire", "Glare"],
				signatureMove: "Dragon Pulse",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
			"Silver": {
				species: "Feraligatr",
				ability: "Sheer Force",
				item: "Life Orb",
				gender: "M",
				moves: ["Waterfall", "Ice Punch", "Crunch"],
				signatureMove: "Dragon Dance",
				evs: {
					atk: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Adamant",
			},
			//Gen 7
			"Ilima": {
				species: "Gumshoos",
				ability: "Adaptability",
				item: "Choice Band",
				gender: "M",
				moves: ["Return", "Crunch", "U-Turn"],
				signatureMove: "Superpower",
				evs: {
					atk: 252,
					def: 4,
					hp: 252,
				},
				nature: "Adamant",
			},
			"Kiawe": {
				species: "Salazzle",
				ability: "Corrosion",
				item: "Focus Sash",
				gender: "M",
				moves: ["Fake Out", "Flamethrower", "Hidden Power Grass"],
				signatureMove: "Sludge Wave",
				evs: {
					spa: 252,
					spe: 252,
					atk: 4,
				},
				nature: "Naive",
			},
			"Mallow": {
				species: "Lurantis",
				ability: "Leaf Guard",
				item: "Leftovers",
				gender: "F",
				moves: ["Leaf Blade", "Defog", "Swords Dance"],
				signatureMove: "leechlife",
				evs: {
					atk: 252,
					def: 4,
					hp: 252,
				},
				nature: "Adamant",
			},
			"Gladion": {
				species: "Silvally",
				ability: "RKS System",
				item: "Steel Memory",
				gender: "M",
				moves: ["Multi-Attack", "Air Slash", "Tri Attack"],
				signatureMove: "Flamethrower",
				evs: {
					spa: 252,
					hp: 4,
					spe: 252,
				},
				nature: "Modest",
			},
			"Hau": {
				species: "Raichu-Alola",
				ability: "Surge Surfer",
				item: "Aloraichium Z",
				gender: "M",
				moves: ["Thunderbolt", "Focus Blast", "Volt Switch"],
				signatureMove: "Psychic",
				evs: {
					spa: 252,
					spd: 4,
					spe: 252,
				},
				nature: "Timid",
			},
			"Lusamine": {
				species: "Nihilego",
				ability: "Beast Boost",
				item: "Choice Scarf",
				gender: "F",
				moves: ["Power Gem", "Dazzling Gleam", "Psychic"],
				signatureMove: "Sludge Wave",
				evs: {
					spa: 252,
					spd: 4,
					spe: 252,
				},
				nature: "Timid",
			},
			"Guzma": {
				species: "Golisopod",
				ability: "Emergency Exit",
				item: "Life Orb",
				gender: "M",
				moves: ["First Impression", "Liquidation", "Leech Life"],
				signatureMove: "Aqua Jet",
				evs: {
					atk: 252,
					def: 4,
					hp: 252,
				},
				nature: "Adamant",
			},
			"Plumeria": {
				species: "Toxapex",
				ability: "Regenerator",
				item: "Black Sludge",
				gender: "F",
				moves: ["Recover", "Scald", "Toxic Spikes"],
				signatureMove: "Baneful Bunker",
				evs: {
					hp: 252,
					def: 252,
					spa: 4,
				},
				nature: "Bold",
			},
			"Olivia": {
				species: "Lycanroc-Midnight",
				ability: "No Guard",
				item: "Life Orb",
				gender: "F",
				moves: ["Stone Edge", "Thunder Fang", "Accelerock"],
				signatureMove: "Sucker Punch",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Kahili": {
				species: "Toucannon",
				ability: "Skill Link",
				item: "Leftovers",
				gender: "F",
				moves: ["Fury Attack", "Brave Bird", "Rock Blast"],
				signatureMove: "Bullet Seed",
				evs: {
					atk: 252,
					def: 4,
					hp: 252,
				},
				nature: "Adamant",
			},
			"Sophocles": {
				species: "Togedemaru",
				ability: "Iron Barbs",
				item: "Air Balloon",
				gender: "M",
				moves: ["Fake Out", "Fell Stinger", "Spiky Shield"],
				signatureMove: "Zing Zap",
				evs: {
					atk: 252,
					def: 4,
					spe: 252,
				},
				nature: "Jolly",
			},
			"Hapu": {
				species: "Mudsdale",
				ability: "Stamina",
				item: "Leftovers",
				gender: "F",
				moves: ["Earthquake", "Rock Slide", "Sleep Talk"],
				signatureMove: "Rest",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Nanu": {
				species: "Persian-Alola",
				ability: "Technician",
				item: "Life Orb",
				gender: "M",
				moves: ["Fake Out", "Night Slash", "Play Rough"],
				signatureMove: "Return",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Hala": {
				species: "Crabombinable",
				ability: "Iron Fist",
				item: "Choice Band",
				gender: "M",
				moves: ["Ice Punch", "Close Combat", "Rock Slide"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					def: 4,
					hp: 252,
				},
				nature: "Adamant",
			},
			"Lana": {
				species: "Wishiwashi",
				ability: "Schooling",
				item: "Leftovers",
				gender: "F",
				moves: ["Waterfall", "Ice Beam", "U-Turn"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					spa: 4,
					hp: 252,
				},
				nature: "Brave",
			},
			"Acerola": {
				species: "Mimikyu",
				ability: "Disguise",
				item: "Normalium Z",
				gender: "F",
				moves: ["Shadow Claw", "Play Rough", "Shadow Sneak"],
				signatureMove: "Splash",
				evs: {
					atk: 252,
					hp: 4,
					spe: 252,
				},
				nature: "Adamant",
			},
			"Kukui": {
				species: "Lycanroc",
				ability: "Sand Rush",
				item: "Life Orb",
				gender: "M",
				moves: ["Rock Slide", "Accelerock", "Thunder Fang"],
				signatureMove: "Sucker Punch",
				evs: {
					atk: 252,
					hp: 4,
					spe: 252,
				},
				nature: "Jolly",
			},
			"Mina": {
				species: "Ribombee",
				ability: "Shield Dust",
				item: "Leftovers",
				gender: "F",
				moves: ["Bug Buzz", "Psychic", "Quiver Dance"],
				signatureMove: "Moonblast",
				evs: {
					spa: 252,
					spd: 4,
					spe: 252,
				},
				nature: "Timid",
			},
			"Faba": {
				species: "Bruxish",
				ability: "Strong Jaw",
				item: "Life Orb",
				gender: "M",
				moves: ["Aqua Jet", "Ice Fang", "Crunch"],
				signatureMove: "Psychic Fangs",
				evs: {
					atk: 252,
					def: 4,
					spe: 252,
				},
				nature: "Jolly",
			},
			"Molayne": {
				species: "Sandslash-Alola",
				ability: "Slush Rush",
				item: "Life Orb",
				gender: "M",
				moves: ["Icicle Crash", "Iron Head", "Earthquake"],
				signatureMove: "Rapid Spin",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			//TODO: Add Lillie, Cyrus, Archie, Maxie,
		};
		// convert moves to ids.
		for (let k in sets) {
			sets[k].moves = sets[k].moves.map(toId);
			sets[k].baseSignatureMove = toId(sets[k].baseSignatureMove);
		}

		// Generate the team randomly.
		let pool = this.shuffle(Object.keys(sets));
		for (let i = 0; i < 6; i++) {
			let set = sets[pool[i]];
			set.level = 100;
			set.name = pool[i];
			if (!set.ivs) {
				set.ivs = {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31};
			} else {
				for (let iv in {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31}) {
					set.ivs[iv] = set.ivs[iv] || set.ivs[iv] === 0 ? set.ivs[iv] : 31;
				}
			}
			// Assuming the hardcoded set evs are all legal.
			if (!set.evs) set.evs = {hp: 84, atk: 84, def: 84, spa: 84, spd: 84, spe: 84};
			set.moves = [this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves)].concat(set.signatureMove);
			team.push(set);
		}
		return team;
	}
}

module.exports = RandomCOTRTeams;
