//Fresh, 100% Ready/

'use strict';

exports.BattlePokedex = {
	pyukumuku: {
		inherit: true,
		species: "Botamon",
		types: ["Fire"],
		baseStats: {
			hp: 35,
			atk: 100,
			def: 50,
			spa: 100,
			spd: 50,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 2.3,
		color: "Black",
		evos: ["Koromon", "Sukamon"],
	},
	vanillite: {
		inherit: true,
		species: "Poyomon",
		types: ["Air"],
		baseStats: {
			hp: 35,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 2.3,
		color: "White",
		evos: ["Tokomon", "Sukamon"],
	},
	darumaka: {
		inherit: true,
		species: "Punimon",
		types: ["Air"],
		baseStats: {
			hp: 35,
			atk: 50,
			def: 100,
			spa: 50,
			spd: 100,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 2.3,
		color: "Red",
		evos: ["Tsunomon", "Sukamon"],
	},
	cascoon: {
		inherit: true,
		species: "Yuramon",
		types: ["Earth"],
		baseStats: {
			hp: 55,
			atk: 50,
			def: 50,
			spa: 50,
			spd: 50,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 2.3,
		color: "White",
		evos: ["Tanemon", "Sukamon"],
	},
	//In-Training, 100% Ready/
	igglybuff: {
		inherit: true,
		species: "Koromon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 50,
			atk: 100,
			def: 50,
			spa: 100,
			spd: 50,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 4.5,
		color: "Pink",
		evos: ["Agumon", "Gabumon", "Kunemon", "Sukamon"],
		prevo: ["Botamon"],
	},
	silcoon: {
		inherit: true,
		species: "Tokomon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 50,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 4.5,
		color: "White",
		evos: ["Patamon", "Biyomon", "Kunemon", "Sukamon"],
		prevos: ["Poyomon"],
	},
	swinub: {
		inherit: true,
		species: "Tsunomon",
		types: ["Air", "Ice"],
		baseStats: {
			hp: 50,
			atk: 50,
			def: 100,
			spa: 50,
			spd: 100,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 4.5,
		color: "Brown",
		evos: ["Elecmon", "Penguinmon", "Kunemon", "Sukamon"],
		prevos: ["Punimon"],
	},
	sunkern: {
		inherit: true,
		species: "Tanemon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 70,
			atk: 50,
			def: 50,
			spa: 50,
			spd: 50,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 4.5,
		color: "Green",
		evos: ["Palmon", "Betamon", "Kunemon", "Sukamon"],
		prevos: ["Yuramon"],
	},
	//Rookie, 100% ready
	helioptile: {
		inherit: true,
		species: "Agumon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 100,
			atk: 200,
			def: 100,
			spa: 200,
			spd: 100,
			spe: 150,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Yellow",
		evo: ["Birdramon", "Centarumon", "Greymon", "Meramon", "Monochromon", "Tyrannomon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Koromon"],
	},
	rockruff: {
		inherit: true,
		species: "Gabumon",
		types: ["Battle", "Fire"],
		baseStats: {
			hp: 100,
			atk: 100,
			def: 200,
			spa: 100,
			spd: 200,
			spe: 200,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 6.8,
		color: "White",
		evo: ["Centarumon", "Drimogemon", "Garurumon", "Monochromon", "Ogremon", "Tyrannomon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Koromon"],
	},
	dedenne: {
		inherit: true,
		species: "Patamon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 120,
			atk: 200,
			def: 200,
			spa: 200,
			spd: 200,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Brown",
		evo: ["Angemon", "Leomon", "Ogremon", "Unimon", "Ogremon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tokomon"],
	},
	electrike: {
		inherit: true,
		species: "Elecmon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 100,
			atk: 200,
			def: 100,
			spa: 200,
			spd: 100,
			spe: 200,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Red",
		evo: ["Angemon", "Leomon", "Kokatorimon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tsunomon"],
	},
	oricoriopau: {
		inherit: true,
		species: "Biyomon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 120,
			atk: 150,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 200,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Pink",
		evo: ["Airdramon", "Birdramon", "Kabuterimon", "Kokatorimon", "Unimon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tokomon"],
	},
	weedle: {
		inherit: true,
		species: "Kunemon",
		types: ["Earth", "Air"],
		baseStats: {
			hp: 100,
			atk: 200,
			def: 100,
			spa: 200,
			spd: 100,
			spe: 130,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Yellow",
		evo: ["Kabuterimon", "Kuwagamon", "Vegiemon"],
		prevo: ["Koromon", "Tokomon", "Tsunomon", "Tanemon", "Sukamon"],
	},
	sunflora: {
		inherit: true,
		species: "Palmon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 120,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 120,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Green",
		evo: ["Coelamon", "Kuwagamon", "Ninjamon", "Vegiemon", "Whamon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tanemon"],
	},
	mudkip: {
		inherit: true,
		species: "Betamon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 100,
			atk: 100,
			def: 200,
			spa: 100,
			spd: 200,
			spe: 130,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Green",
		evo: ["Coelamon", "Drimogemon", "Seadramon", "Shellmon", "Whamon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tanemon"],
	},
	delibird: {
		inherit: true,
		species: "Penguinmon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 120,
			atk: 100,
			def: 200,
			spa: 100,
			spd: 200,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 6.8,
		color: "Blue",
		evo: ["Fridgimon", "Garurumon", "Mojaymon", "Shellmon", "Whamon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tsunomon"],
	},
	//Champion/
	heliolisk: {
		inherit: true,
		species: "Greymon",
		types: ["Fire", "Battle", "Air"],
		baseStats: {
			hp: 170,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 250,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Brown",
		evo: ["MetalGreymon", "SkullGreymon", "Vademon"],
		prevo: ["Agumon"],
	},
	rhyhorn: {
		inherit: true,
		species: "Monochromon",
		types: ["Fire", "Battle", "Earth"],
		baseStats: {
			hp: 220,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 18.1,
		color: "Gray",
		evo: ["MetalGreymon", "MetalMamemon", "Vademon"],
		prevo: ["Agumon", "Gabumon"],
	},
	marowak: {
		inherit: true,
		species: "Ogremon",
		types: ["Battle", "Fire", "Earth"],
		baseStats: {
			hp: 200,
			atk: 300,
			def: 300,
			spa: 300,
			spd: 300,
			spe: 100,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Green",
		evo: ["Andromon", "Giromon", "Vademon"],
		prevo: ["Gabumon", "Patamon"],
	},
	altaria: {
		inherit: true,
		species: "Airdramon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 170,
			atk: 200,
			def: 100,
			spa: 200,
			spd: 100,
			spe: 400,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Blue",
		evo: ["Megadramon", "Phoenixmon", "Vademon"],
		prevo: ["Biyomon"],
	},
	buzzwole: {
		inherit: true,
		species: "Kuwagamon",
		types: ["Earth", "Battle", "Air"],
		baseStats: {
			hp: 220,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 100,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Red",
		evo: ["HerculesKabuterimon", "Piximon", "Vademon"],
		prevo: ["Kunemon", "Palmon"],
	},
	wailord: {
		inherit: true,
		species: "Whamon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 220,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 18.1,
		color: "Blue",
		evo: ["Mamemon", "MegaSeadramon", "Vademon"],
		prevo: ["Betamon", "Palmon", "Penguinmon"],
	},
	beartic: {
		inherit: true,
		species: "Frigimon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 220,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 100,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 18.1,
		color: "Blue",
		evo: ["Mamemon", "MetalMamemon", "Vademon"],
		prevo: ["Penguinmon"],
	},
	electrode: {
		inherit: true,
		species: "Nanimon",
		types: ["Filth", "Battle"],
		baseStats: {
			hp: 150,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 100,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 2.3,
		color: "Brown",
		evo: ["Digitamamon", "Vademon"],
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
	},
	magmar: {
		inherit: true,
		species: "Meramon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 150,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 160,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 9.1,
		color: "Red",
		evo: ["Andromon", "MetalGreymon", "Vademon"],
		prevo: ["Agumon"],
	},
	excadrill: {
		inherit: true,
		species: "Drimogemon",
		types: ["Battle", "Earth"],
		baseStats: {
			hp: 150,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 300,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 18.1,
		color: "Purple",
		evo: ["MetalGreymon", "Vademon"],
		prevo: ["Betamon", "Gabumon"],
	},
	pyroar: {
		inherit: true,
		species: "Leomon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 170,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 9.1,
		color: "Yellow",
		evo: ["Andromon", "Mamemon", "Vademon"],
		prevo: ["Elecmon", "Patamon"],
	},
	combusken: {
		inherit: true,
		species: "Kokatorimon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 170,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 13.6,
		color: "White",
		evo: ["Andromon", "Mamemon", "Vademon"],
		prevo: ["Elecmon", "Patamon"],
	},
	carnivine: {
		inherit: true,
		species: "Vegiemon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 150,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 130,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 4.5,
		color: "Green",
		evo: ["Piximon", "Vademon"],
		prevo: ["Kunemon", "Palmon"],
	},
	crustle: {
		inherit: true,
		species: "Shellmon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 220,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 18.1,
		color: "Pink",
		evo: ["MegaSeadramon", "HerculesKabuterimon", "Vademon"],
		prevo: ["Betamon", "Pengiunmon"],
	},
	vigoroth: {
		inherit: true,
		species: "Mojyamon",
		types: ["Ice", "Battle", "Earth"],
		baseStats: {
			hp: 200,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 100,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 9.1,
		color: "White",
		evo: ["Mamemon", "SkullGreymon", "Vademon"],
		prevo: ["Penguinmon"],
	},
	moltres: {
		inherit: true,
		species: "Birdramon",
		types: ["Fire", "Air"],
		baseStats: {
			hp: 150,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 305,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 9.1,
		color: "Red",
		evo: ["Phoenixmon", "Vademon"],
		prevo: ["Agumon", "Biyomon"],
	},
	tyrantrum: {
		inherit: true,
		species: "Tyrannomon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 200,
			atk: 300,
			def: 300,
			spa: 300,
			spd: 300,
			spe: 150,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "Red",
		weightkg: 13.6,
		prevo: ["Agumon", "Gabumon", "Patamon"],
		evo: ["MetalGreymon", "Megadramon", "Vademon"],
	},
	togetic: {
		inherit: true,
		species: "Angemon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 170,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 9.1,
		color: "White",
		prevo: ["Elecmon", "Patamon"],
		evo: ["Andromon", "Devimon", "Phoenixmon", "Vademon"],
	},
	rapidash: {
		inherit: true,
		species: "Unimon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 200,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 13.6,
		color: "White",
		prevo: ["Biyomon", "Patamon"],
		evo: ["Giromon", "Phoenixmon", "Vademon"],
	},
	accelgor: {
		inherit: true,
		species: "Ninjamon",
		types: ["Earth", "Battle", "Fire"],
		baseStats: {
			hp: 150,
			atk: 150,
			def: 150,
			spa: 150,
			spd: 150,
			spe: 150,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 4.5,
		color: "Red",
		prevo: ["Palmon"],
		evo: ["Mamemon", "Metalmamemon", "Piximon", "Vademon"],
	},
	relicanth: {
		inherit: true,
		species: "Coelamon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 150,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 13.6,
		color: "White",
		prevo: ["Betamon", "Palmon"],
		evo: ["MegaSeadramon", "Vademon"],
	},
	muk: {
		inherit: true,
		species: "Numemon",
		types: ["Filth"],
		baseStats: {
			hp: 150,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 2.3,
		color: "Green",
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
		evo: ["Monzemon", "Vademon"],
	},
	mudsdale: {
		inherit: true,
		species: "Centarumon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 170,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Brown",
		prevo: ["Agumon", "Gabumon"],
		evo: ["Andromon", "Giromon", "Vademon"],
	},
	banette: {
		inherit: true,
		species: "Devimon",
		types: ["Battle", "Air", "Ice"],
		baseStats: {
			hp: 170,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 9.1,
		color: "Black",
		prevo: ["Angemon"],
		evo: ["Megadramon", "SkullGreymon", "Vademon"],
	},
	mimikyu: {
		inherit: true,
		species: "Bakemon",
		types: ["Air", "Ice"],
		baseStats: {
			hp: 150,
			atk: 170,
			def: 170,
			spa: 170,
			spd: 170,
			spe: 170,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 9.1,
		color: "White",
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
		evo: ["SkullGreymon", "Giromon", "Vademon"],
	},
	heracross: {
		inherit: true,
		species: "Kabuterimon",
		types: ["Earth", "Fire", "Air"],
		baseStats: {
			hp: 200,
			atk: 300,
			def: 100,
			spa: 300,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Blue",
		prevo: ["Biyomon", "Kunemon"],
		evo: ["HerculesKabuterimon", "MetalMamemon", "Vademon"],
	},
	dragonair: {
		inherit: true,
		species: "Seadramon",
		types: ["Ice", "Earth", "Fire"],
		baseStats: {
			hp: 200,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 100,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		weightkg: 13.6,
		color: "Blue",
		prevo: ["Betamon"],
		evo: ["MegaSeadramon", "Megadramon", "Vademon"],
	},
	lycanroc: {
		inherit: true,
		species: "Garurumon",
		types: ["Ice", "Fire", "Battle"],
		baseStats: {
			hp: 150,
			atk: 100,
			def: 300,
			spa: 100,
			spd: 300,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		weightkg: 13.6,
		color: "White",
		prevo: ["Gabumon", "Penguinmon"],
		evo: ["MegaSeadramon", "SkullGreymon", "Vademon"],
	},
	garbodor: {
		inherit: true,
		species: "Sukamon",
		types: ["Filth"],
		baseStats: {
			hp: 150,
			atk: 100,
			def: 100,
			spa: 100,
			spd: 100,
			spe: 100,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		weightkg: 2.3,
		color: "Yellow",
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
		evo: ["Etemon", "Vademon"],
	},
	//Ultimate Digimon
	druddigon: {
		inherit: true,
		species: "MetalGreymon",
		types: ["Mech", "Fire", "Battle"],
		baseStats: {
			hp: 400,
			atk: 500,
			def: 500,
			spa: 500,
			spd: 500,
			spe: 300,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		color: "Purple",
		weightkg: 22.7,
		prevos: ["Greymon", "Monochromon"],
	},
	aggron: {
		inherit: true,
		species: "SkullGreymon",
		types: ["Battle", "Ice", "Mech"],
		baseStats: {
			hp: 400,
			atk: 400,
			def: 400,
			spa: 400,
			spd: 400,
			spe: 200,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		color: "White",
		weightkg: 13.6,
		prevos: ["Bakemon", "Devimon", "Garurumon", "Greymon", "Mojyamon"],
	},
	pawniard: {
		inherit: true,
		species: "Giromon",
		types: ["Mech", "Air", "Battle"],
		baseStats: {
			hp: 200,
			atk: 400,
			def: 100,
			spa: 400,
			spd: 100,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		color: "Purple",
		weightkg: 2.3,
		prevos: ["Bakemon", "Centarumon", "Ogremon", "Unimon"],
	},
	pinsirmega: {
		inherit: true,
		species: "HerculesKabuterimon",
		types: ["Earth", "Battle", "Fire"],
		baseStats: {
			hp: 300,
			atk: 500,
			def: 400,
			spa: 500,
			spd: 400,
			spe: 400,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "Yellow",
		weightkg: 18.1,
		prevos: ["Kabuterimon", "Kuwagamon", "Shellmon"],
	},
	chingling: {
		inherit: true,
		species: "Mamemon",
		types: ["Battle", "Mech"],
		baseStats: {
			hp: 100,
			atk: 400,
			def: 300,
			spa: 400,
			spd: 300,
			spe: 300,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "Gray",
		weightkg: 2.3,
		prevos: ["Frigimon", "Leomon", "Mojyamon", "Ninjamon", "Whamon"],
	},
	gyarados: {
		inherit: true,
		species: "MegaSeadramon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 300,
			atk: 500,
			def: 500,
			spa: 500,
			spd: 500,
			spe: 200,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "Red",
		weightkg: 13.6,
		prevos: ["Coelamon", "Garurumon", "Seadramon", "Shellmon", "Whamon"],
	},
	beheeyem: {
		inherit: true,
		species: "Vademon",
		types: ["Mech", "Earth"],
		baseStats: {
			hp: 199,
			atk: 199,
			def: 199,
			spa: 199,
			spd: 199,
			spe: 199,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		color: "Pink",
		weightkg: 2.3,
		prevos: ["Airdramon", "Angemon", "Bakemon", "Birdramon", "Centarumon", "Coelamon", "Devimon", "Drimogemon", "Frigimon", "Garurumon", "Greymon", "Kabuterimon", "Kokatorimon", "Kuwagamon", "Leomon", "Meramon", "Mojyamon", "Monochromon", "Nanimon", "Numemon", "Ogremon", "Seadramon", "Shellmon", "Sukamon", "Tyrannomon", "Unimon", "Vegiemon", "Whamon"],
	},
	simisear: {
		inherit: true,
		species: "Etemon",
		types: ["Battle", "Air", "Filth"],
		baseStats: {
			hp: 200,
			atk: 400,
			def: 200,
			spa: 400,
			spd: 200,
			spe: 400,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		color: "Brown",
		weightkg: 6.8,
		prevos: ["Sukamon"],
	},
	registeel: {
		inherit: true,
		species: "Andromon",
		types: ["Mech", "Battle", "Air"],
		baseStats: {
			hp: 200,
			atk: 200,
			def: 400,
			spa: 200,
			spd: 400,
			spe: 200,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		color: "Gray",
		weightkg: 18.1,
		prevos: ["Angemon", "Centarumon", "Meramon", "Ogremon"],
	},
	zygarde: {
		inherit: true,
		species: "Megadramon",
		types: ["Mech", "Ice", "Battle"],
		baseStats: {
			hp: 300,
			atk: 500,
			def: 300,
			spa: 500,
			spd: 300,
			spe: 400,
		},
		abilities: {
			0: "Virus",
		},
		inherit: true,
		color: "Red",
		weightkg: 24.9,
		prevos: ["Airdramon", "Devimon", "Seadramon", "Tyrannomon"],
	},
	hooh: {
		inherit: true,
		species: "Phoenixmon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 500,
			atk: 200,
			def: 200,
			spa: 200,
			spd: 200,
			spe: 500,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		color: "Yellow",
		weightkg: 13.6,
		prevos: ["Aidramon", "Angemon", "Birdramon", "Kokatorimon", "Unimon"],
	},
	jigglypuff: {
		inherit: true,
		species: "Piximon",
		types: ["Earth", "Air"],
		baseStats: {
			hp: 100,
			atk: 300,
			def: 300,
			spa: 300,
			spd: 300,
			spe: 400,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "Pink",
		weightkg: 2.3,
		prevos: ["Kokatorimon", "Kuwagamon", "Ninjamon", "Vegiemon"],
	},
	ferroseed: {
		inherit: true,
		species: "MetalMamemon",
		types: ["Battle", "Mech"],
		baseStats: {
			hp: 100,
			atk: 500,
			def: 400,
			spa: 500,
			spd: 400,
			spe: 400,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "Gray",
		weightkg: 4.6,
		prevos: ["Frigimon", "Kabuterimon", "Monochromon", "Ninjamon"],
	},
	bewear: {
		inherit: true,
		species: "Monzaemon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 300,
			atk: 300,
			def: 300,
			spa: 300,
			spd: 300,
			spe: 300,
		},
		abilities: {
			0: "Vaccine",
		},
		inherit: true,
		color: "Yellow",
		weightkg: 18.1,
		prevos: ["Numemon"],
	},
	togepi: {
		inherit: true,
		species: "DigiTamamon",
		types: ["Fire", "Air", "Ice"],
		baseStats: {
			hp: 300,
			atk: 400,
			def: 400,
			spa: 400,
			spd: 400,
			spe: 400,
		},
		abilities: {
			0: "Data",
		},
		inherit: true,
		color: "White",
		weightkg: 4.5,
		prevos: ["Nanimon"],
	},
	//Mega Digimon
	genesect: {
		inherit: true,
		species: "Machinedramon",
		types: ["Mech", "Air", "Battle"],
		baseStats: {
			hp: 940,
			atk: 500,
			def: 500,
			spa: 500,
			spd: 500,
			spe: 100,
		},	
		abilities: {
			0: "Virus",
		},
		inherit: true,
		color: "Gray",
		weightkg: 36.3,
	},
};
