'use strict';

exports.BattleLearnsets = {
	smk: {
		learnset: {
			outrage: ["7L1", "7L60"],
			tackle: ["7L1"],
			bite: ["7L3"],
			crunch: ["7L15"],
			foulplay: ["7L29"],
			explosion: ["7M", "7L37"],
			agility: ["7L42"],
			selfdestruct: ["7L32"],
			headsmash: ["7L62"],
			astonish: ["7L5"],
			nightshade: ["7L17"],
			shadowpunch: ["7L15"],
			knockoff: ["7L29"],
			spectralthief: ["7L45"],
			endeavor: ["7L4"],
			headbutt: ["7L13"],
			doubleteam: ["7L49", "7M"],
			workup: ["7M"],
			calmmind: ["7M"],
			bulkup: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			protect: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			brickbreak: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			snarl: ["7M"],
			confide: ["7M"],
			drinkbleach: ["7L70"],
		},
	},
	musteltank: {
		learnset: {
			poisonjab: ["7M"],
			ironhead: ["7L56"],
			earthquake: ["7M"],
			honeclaws: ["7M"],
			bulkup: ["7M"],
			dig: ["7M"],
			superpower: ["7L46"],
			irontail: ["7L24"],
			heavyslam: ["7L36"],
			protect: ["7M"],
			toxic: ["7M"],
			growl: ["7L1"],
			screech: ["7L6"],
			irondefense: ["7L26"],
			rollout: ["7L8"],
			banefulbunker: ["7L53"],
			rapidspin: ["7L42"],
			rest: ["7M"],
			sleeptalk: ["7M"],
			recycle: ["7L9"],
			poisongas: ["7L3"],
			metalsound: ["7L13"],
			metalclaw: ["7L21"],
			suckerpunch: ["7L29"],
			trickroom: ["7M"],
		},
	},
	pence: {
		learnset: {
			protect: ["7M"],
			drainpunch: ["7L45"],
			closecombat: ["7L57"],
			playrough: ["7L58"],
			suckerpunch: ["7L20"],
			knockoff: ["7L3"],
			tackle: ["7L1"],
			icepunch: ["7L13"],
			earthquake: ["7M"],
			superpower: ["7L45"],
			moonblast: ["7L33"],
			focusblast: ["7L59"],
			aurasphere: ["7L86"],
		},
	},
	frioth: {
		learnset: {
			wideguard: ["7L1"],
			strugglebug: ["7L1"],
			aquaring: ["7L1"],
			powdersnow: ["7L8"],
			bugbite: ["7L10", "7E"],
			iceshard: ["7L16"],
			bugbuzz: ["7L22"],
			mirrorcoat: ["7L34"],
			hail: ["7L39", "7M"],
			quiverdance: ["7L45"],
			aurorabeam: ["7L48"],
			iciclecrash: ["7L51"],
			iciclespear: ["7L51"],
			blizzard: ["7L56", "7M"],
			swordsdance: ["7L63", "7M"],
			workup: ["7M"],
			calmmind: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			icebeam: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			falseswipe: ["7M"],
			skydrop: ["7M"],
			quash: ["7M"],
			acrobatics: ["7M"],
			gigaimpact: ["7M"],
			auroraveil: ["7M"],
			fly: ["7M"],
			psychup: ["7M"],
			frostbreath: ["7M"],
			xscissor: ["7M"],
			infestation: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			surf: ["7M"],
			naturepower: ["7M"],
			waterfall: ["7M"],
			dazzlinggleam: ["7M"],
			confide: ["7M"],
			acupressure: ["7E"],
			crosspoison: ["7E"],
			pinmissle: ["7E"],
			icehammer: ["7E"],
			spikecannon: ["7E"],
			spikes: ["7E"],
			snore: ["7T"],
			waterpulse: ["7T"],
			signalbeam: ["7T"],
			icepunch: ["7T"],
			knockoff: ["7T"],
			dualchop: ["7T"],
			endeavor: ["7T"],
			uproar: ["7T"],
			ironhead: ["7T"],
			aquatail: ["7T"],
			lastresort: ["7T"],
			hypervoice: ["7T"],
			skyattack: ["7T"],
			block: ["7T"],
			recycle: ["7T"],
			irondefense: ["7T"],
			tailwind: ["7T"],
			electroweb: ["7T"],
			icywind: ["7T"],
		},
	},
	octanko: {
		learnset: {
			attract: ["7M", "6M", "5M", "4M", "3M"],
			aurorabeam: ["7L14", "7L1", "6L1", "5L1", "4L1", "3L22"],
			bind: ["6T", "5T"],
			blizzard: ["7M", "6M", "5M", "4M", "3M"],
			bounce: ["6T", "5T", "4T"],
			brine: ["4M"],
			bubblebeam: ["7L18", "6L18", "5L19", "4L19", "3L22"],
			bulletseed: ["7L46", "6L46", "5L29", "4M", "4L29", "3M"],
			captivate: ["4M"],
			chargebeam: ["7M", "6M", "5M", "4M"],
			confide: ["7M", "6M"],
			constrict: ["7L6", "7L1", "6L1", "5L1", "4L1", "3L11"],
			defensecurl: ["3T"],
			dive: ["6M", "5M", "4T", "3M"],
			doubleedge: ["3T"],
			doubleteam: ["7M", "6M", "5M", "4M", "3M"],
			endure: ["4M", "3T"],
			energyball: ["7M", "6M", "5M", "4M"],
			facade: ["7M", "6M", "5M", "4M", "3M"],
			fireblast: ["7M", "6M", "5M", "4M", "3M"],
			flamethrower: ["7M", "6M", "5M", "4M", "3M"],
			flashcannon: ["7M", "6M", "5M", "4M"],
			focusenergy: ["7L22", "6L22", "5L23", "4L23", "3L38"],
			frustration: ["7M", "6M", "5M", "4M", "3M"],
			gigaimpact: ["7M", "6M", "5M", "4M"],
			gunkshot: ["7L1", "6T", "6L1", "5T", "5L1", "4T", "4L1"],
			hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
			hurricane: ["7L57"],
			hydropump: ["7L52", "6L52", "5L52"],
			hyperbeam: ["7M", "7L58", "6M", "6L58", "5M", "5L55", "4M", "4L55", "4S0", "3M", "3L70"],
			icebeam: ["7M", "7L40", "6M", "6L40", "5M", "5L48", "4M", "4L48", "4S0", "3M", "3L54"],
			icywind: ["6T", "5T", "4T"],
			incinerate: ["6M", "5M"],
			mimic: ["3T"],
			mudslap: ["4T", "3T"],
			naturalgift: ["4M"],
			octazooka: ["7L1", "6L25", "5L25", "4L25", "4S0", "3L25"],
			payback: ["7M", "6M", "5M", "4M"],
			protect: ["7M", "6M", "5M", "4M", "3M"],
			psybeam: ["7L10", "7L1", "6L1", "5L1", "4L1", "3L22"],
			psychic: ["7M", "6M", "5M", "4M", "3M"],
			raindance: ["7M", "6M", "5M", "4M", "3M"],
			rest: ["7M", "6M", "5M", "4M", "3M"],
			recover: ["7L56"],
			return: ["7M", "6M", "5M", "4M", "3M"],
			rockblast: ["7L1", "6L1", "5L1", "4L1"],
			round: ["7M", "6M", "5M"],
			scald: ["7M", "6M", "5M"],
			secretpower: ["6M", "4M", "3M"],
			seedbomb: ["6T", "5T", "4T"],
			seismictoss: ["3T"],
			signalbeam: ["7L34", "6T", "6L34", "5T", "5L42", "4T", "4L42", "4S0"],
			sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
			sludgebomb: ["7M", "6M", "5M", "4M", "3M"],
			sludgewave: ["7M", "6M", "5M"],
			smackdown: ["7M", "6M", "5M"],
			snore: ["6T", "5T", "4T", "3T"],
			soak: ["7L64", "6L64", "5L61"],
			stringshot: ["4T"],
			substitute: ["7M", "6M", "5M", "4M", "3T"],
			sunnyday: ["7M", "6M", "5M", "4M", "3M"],
			surf: ["7M", "6M", "5M", "4M", "3M"],
			swagger: ["7M", "6M", "5M", "4M", "3T"],
			swift: ["4T", "3T"],
			thief: ["7M", "6M", "5M", "4M", "3M"],
			thunderwave: ["7M", "6M", "5M", "4M", "3T"],
			toxic: ["7M", "6M", "5M", "4M", "3M"],
			waterfall: ["7M", "6M", "5M", "4M", "3M"],
			watergun: ["7L1", "6L1", "5L1", "4L1", "3L1"],
			waterpulse: ["6T", "4M", "3M"],
			whirlpool: ["4M"],
			wringout: ["7L28", "6L28", "5L36", "4L36"],
		},
	},
	spectreon: {
		learnset: {
			workup: ["7M"],
			fakeout: ["7M"],
			dazzlinggleam: ["7M"],
			boomburst: ["7M"],
			frostbreath: ["7M"],
			shadowball: ["7M"],
			darkpulse: ["7M"],
			hypnosis: ["7M"],
			knockoff: ["7M"],
			shadowclaw: ["7M"],
			frustration: ["7M"],
			reversal: ["7M"],
			suckerpunch: ["7M"],
			willowisp: ["7M"],
			focusblast: ["7M"],
			sacredfire: ["7M"],
			nastyplot: ["7M"],
		},
	},
	hydring: {
		learnset: {
			magnetbomb: ["7L1"],
			ironhead: ["7L23"],
			thunderbolt: ["7M"],
			grassknot: ["7M"],
			surf: ["7M"],
			waterfall: ["7M"],
			protect: ["7M"],
			scald: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			raindance: ["7M"],
			icebeam: ["7M"],
			blizzard: ["7M"],
		},
	},
	yinyang: {
		learnset: {
			overheat: ["7M"],
			flamethrower: ["7M"],
			willowisp: ["7M"],
			iciclecrash: ["7M"],
			freezedry: ["7M"],
			icefang: ["7M"],
			auroraveil: ["7M"],
			hypervoice: ["7M"],
			weatherball: ["7M"],
			fakeout: ["7M"],
			naturepower: ["7M"],
			roar: ["7M"],
			encore: ["7M"],
			yawn: ["7M"],
			bugbuzz: ["7M"],
			snarl: ["7M"],
			disarmingvoice: ["7M"],
			shadowball: ["7M"],
			shadowforce: ["7M"],
			hex: ["7M"],
			confuseray: ["7M"],
			razorleaf: ["7M"],
			magicalleaf: ["7M"],
			earthpower: ["7M"],
			clearsmog: ["7M"],
			zenheadbutt: ["7M"],
			powersplit: ["7M"],
			guardsplit: ["7M"],
			powerswap: ["7M"],
			speedswap: ["7M"],
			skillswap: ["7M"],
			metalsound: ["7M"],
			surf: ["7M"],
			aquajet: ["7M"],
		},
	},
	reainein: {
		learnset: {
			bugbite: ["7M"],
			firepunch: ["7M"],
			uturn: ["7M"],
			dragonclaw: ["7M"],
		},
	},
	bezzoseal: {
		learnset: {
			bugbite: ["7M"],
			spark: ["7M"],
			lunge: ["7M"],
			finalgambit: ["7M"],
			xscissor: ["7M"],
			slash: ["7M"],
			smartstrike: ["7M"],
			sacredsword: ["7M"],
			shadowsneak: ["7M"],
			phantomforce: ["7M"],
			shadowforce: ["7M"],
			uturn: ["7M"],
			sleeptalk: ["7M"],
			metalclaw: ["7M"],
			rocktomb: ["7M"],
			terrordrop: ["7M"],
		},
	},
};
