'use strict';

exports.commands = {
	smk: function (target, room, user, connection, cmd) {
		if (!this.runBroadcast()) return;
		this.sendReplyBox(
			'<div class="message"><ul class="utilichart"><li class="result"><span class="col numcol"><b>Fakemons</b></span> <span class="col iconcol"><span style="background:transparent url(//imgur.com/5ElSiQ1.png) no-repeat scroll -40px -2430px"></span></span> <span class="col pokemonnamecol" style="white-space:nowrap"><a href="https://github.com/ExiledPS/Team-Exiled/blob/master/mods/fakemons/README.md" target="_blank">SMK</span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Dark.png" alt="Dark" height="14" width="32"></span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Ghost.png" alt="Ghost" height="14" width="32"></span><span style="float:left;min-height:26px"><span class="col abilitycol">Midlife Crisis / Prankster</span><span class="col abilitycol"></span></span><span style="float:left;min-height:26px"><span class="col statcol"><em>HP</em><br>65</span> <span class="col statcol"><em>Atk</em><br>120</span> <span class="col statcol"><em>Def</em><br>40</span> <span class="col statcol"><em>SpA</em><br>20</span> <span class="col statcol"><em>SpD</em><br>40</span> <span class="col statcol"><em>Spe</em><br>140</span> <span class="col bstcol"><em>BST<br>425</em></span> </span></li><li style="clear:both"></li></ul></div>'
		);
	},
	musteltank: function (target, room, user, connection, cmd) {
		if (!this.runBroadcast()) return;
		this.sendReplyBox(
			'<div class="message"><ul class="utilichart"><li class="result"><span class="col numcol"><b>Fakemons</b></span> <span class="col iconcol"><span style="background:transparent url(http://vignette3.wikia.nocookie.net/ethereal-gates/images/3/3c/052.png/revision/latest?cb=20150824222954) no-repeat scroll -40px -2430px"></span></span> <span class="col pokemonnamecol" style="white-space:nowrap"><a href="https://github.com/ExiledPS/Team-Exiled/blob/master/mods/fakemons/README.md#musteltank" target="_blank">Musteltank</span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Poison.png" alt="Poison" height="14" width="32"></span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Steel.png" alt="Steel" height="14" width="32"></span><span style="float:left;min-height:26px"><span class="col abilitycol">Tough Claws / Battle Armor / Rust</span><span class="col abilitycol"></span></span><span style="float:left;min-height:26px"><span class="col statcol"><em>HP</em><br>100</span> <span class="col statcol"><em>Atk</em><br>115</span> <span class="col statcol"><em>Def</em><br>110</span> <span class="col statcol"><em>SpA</em><br>40</span> <span class="col statcol"><em>SpD</em><br>100</span> <span class="col statcol"><em>Spe</em><br>5</span> <span class="col bstcol"><em>BST<br>470</em></span> </span></li><li style="clear:both"></li></ul></div>'
		);
	},
	pence: function (target, room, user, connection, cmd) {
		if (!this.runBroadcast()) return;
		this.sendReplyBox(
			'<div class="message"><ul class="utilichart"><li class="result"><span class="col numcol"><b>Fakemons</b></span> <span class="col iconcol"><span style="background:transparent url(https://res.cloudinary.com/crowdpac/image/upload/d_avatar_m/v1/candidates/cand10361902.jpg) no-repeat scroll -40px -2430px"></span></span> <span class="col pokemonnamecol" style="white-space:nowrap"><a href="https://github.com/ExiledPS/Team-Exiled/blob/master/mods/fakemons/README.md#pence" target="_blank">Pence</span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Fairy.png" alt="Fairy" height="14" width="32"></span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Fighting.png" alt="Fighting" height="14" width="32"></span><span style="float:left;min-height:26px"><span class="col abilitycol">Contrary</span><span class="col abilitycol"></span></span><span style="float:left;min-height:26px"><span class="col statcol"><em>HP</em><br>70</span> <span class="col statcol"><em>Atk</em><br>150</span> <span class="col statcol"><em>Def</em><br>110</span> <span class="col statcol"><em>SpA</em><br>150</span> <span class="col statcol"><em>SpD</em><br>70</span> <span class="col statcol"><em>Spe</em><br>45</span> <span class="col bstcol"><em>BST<br>595</em></span> </span></li><li style="clear:both"></li></ul></div>'
		);
	},
	frioth: function (target, room, user, connection, cmd) {
		if (!this.runBroadcast()) return;
		this.sendReplyBox(
			'<div class="message"><ul class="utilichart"><li class="result"><span class="col numcol"><b>Fakemons</b></span> <span class="col iconcol"><span style="background:transparent url() no-repeat scroll -40px -2430px"></span></span> <span class="col pokemonnamecol" style="white-space:nowrap"><a href="https://github.com/ExiledPS/Team-Exiled/blob/master/mods/fakemons/README.md#frioth" target="_blank">Frioth</span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Bug.png" alt="Bug" height="14" width="32"></span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Ice.png" alt="Ice" height="14" width="32"></span><span style="float:left;min-height:26px"><span class="col abilitycol">Ice Body / Snow Cloak / Aerilate</span><span class="col abilitycol"></span></span><span style="float:left;min-height:26px"><span class="col statcol"><em>HP</em><br>80</span> <span class="col statcol"><em>Atk</em><br>110</span> <span class="col statcol"><em>Def</em><br>100</span> <span class="col statcol"><em>SpA</em><br>90</span> <span class="col statcol"><em>SpD</em><br>75</span> <span class="col statcol"><em>Spe</em><br>90</span> <span class="col bstcol"><em>BST<br>545</em></span> </span></li><li style="clear:both"></li></ul></div>'
		);
	},
	octanko: function (target, room, user, connection, cmd) {
		if (!this.runBroadcast()) return;
		this.sendReplyBox(
			'<div class="message"><ul class="utilichart"><li class="result"><span class="col numcol"><b>Fakemons</b></span> <span class="col iconcol"><span style="background:transparent url() no-repeat scroll -40px -2430px"></span></span> <span class="col pokemonnamecol" style="white-space:nowrap"><a href="https://github.com/ExiledPS/Team-Exiled/blob/master/mods/fakemons/README.md#Octanko" target="_blank">Octanko</span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Water.png" alt="Water" height="14" width="32"></span> <span class="col typecol"><img src="//play.pokemonshowdown.com/sprites/types/Steel.png" alt="Steel" height="14" width="32"></span><span style="float:left;min-height:26px"><span class="col abilitycol">Shell Armor / Sniper / Regenerator</span><span class="col abilitycol"></span></span><span style="float:left;min-height:26px"><span class="col statcol"><em>HP</em><br>90</span> <span class="col statcol"><em>Atk</em><br>105</span> <span class="col statcol"><em>Def</em><br>125</span> <span class="col statcol"><em>SpA</em><br>110</span> <span class="col statcol"><em>SpD</em><br>85</span> <span class="col statcol"><em>Spe</em><br>40</span> <span class="col bstcol"><em>BST<br>555</em></span> </span></li><li style="clear:both"></li></ul></div>'
		);
	},
};
