'use strict';

exports.BattleLearnsets = {
	araquerain: {learnset: {
		blizzard: ["7M"],
		bubblebeam: ["7M"],
		stickywebs: ["7M"],
		doubleedge: ["7M"],
		liquidation: ["7M"],
		poisonjab: ["7M"],
		surf: ["7M"],
		icebeam: ["7M"],
		hydropump: ["7M"],
		bugbuzz: ["7M"],
		xscissor: ["7M"],
		lunge: ["7M"],
		leechlife: ["7M"],
		rest: ["7M"],
		protect: ["7M"],
		quiverdance: ["7M"],
		submission: ["7M"],
		swordsdance: ["7M"],
		uturn: ["7M"],
		waterfall: ["7M"],
		scald: ["7M"],
		hiddenpower: ["7M"],
		toxic: ["7M"],
		gigadrain: ["7M"],
		waterpulse: ["7M"],
	}},
};