"use strict";

const RandomTeams = require("../../data/random-teams");

class RandomAshTeams extends RandomTeams {
	randomAshTeam() {
		let team = [];
		let sets = {
			"Pikachu": {
				species: "Pikachu",
				ability: "Static",
				item: "Light Ball",
				moves: ["Knock Off", "Fake Out", "Extreme Speed"],
				signatureMove: "Volt Tackle",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Butterfree": {
				species: "Butterfree",
				ability: "Compound Eyes",
				item: "Focus Sash",
				moves: ["Quiver Dance", "Hurricane", "Sleep Powder"],
				signatureMove: "Bug Buzz",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Primeape": {
				species: "Primeape",
				ability: "Vital Spirit",
				item: "Choice Scarf",
				moves: ["U-Turn", "Earthquake", "Stone Edge"],
				signatureMove: "Close Combat",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Charizard": {
				species: "Charizard",
				ability: "Solar Power",
				item: "Life Orb",
				moves: ["Flamethrower", "Air Slash", "Sunny Day"],
				signatureMove: "Solar Beam",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Venusaur": {
				species: "Venusaur",
				ability: "Chlorophyll",
				item: "Black Sludge",
				moves: ["Giga Drain", "Knock Off", "Synthesis"],
				signatureMove: "Sludge Bomb",
				evs: {
					hp: 248,
					def: 204,
					spa: 24,
					spd: 16,
					spe: 16,
				},
				nature: "Bold",
			},
			"Blastoise": {
				species: "Blastoise",
				ability: "Rain Dish",
				item: "Leftovers",
				moves: ["Rapid Spin", "Refresh", "Toxic"],
				signatureMove: "Scald",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Bold",
			},
			"Pidgeot": {
				species: "Pidgeot",
				ability: "Tangled Feet",
				item: "Life Orb",
				moves: ["Brave Bird", "Double-Edge", "Defog"],
				signatureMove: "U-Turn",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Kingler": {
				species: "Kingler",
				ability: "Sheer Force",
				item: "Life Orb",
				moves: ["Knock Off", "Rock Slide", "Swords Dance"],
				signatureMove: "Crabhammer",
				evs: {
					atk: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Jolly",
			},
			"Snorlax": {
				species: "Snorlax",
				ability: "Immunity",
				item: "Leftovers",
				moves: ["Body Slam", "Rest", "Sleep Talk"],
				signatureMove: "Curse",
				evs: {
					hp: 252,
					spd: 252,
					def: 4,
				},
				nature: "Careful",
			},
			"Muk": {
				species: "Muk",
				ability: "Poison Touch",
				item: "Black Sludge",
				moves: ["Gunk Shot", "Curse", "Pain Split"],
				signatureMove: "Shadow Sneak",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Bayleef": {
				species: "Bayleef",
				item: "Eviolite",
				ability: "Leaf Guard",
				moves: ["Giga Drain", "Toxic", "Synthesis"],
				signatureMove: "Aromatherapy",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Bold",
			},
			"Noctowl": {
				species: "Noctowl",
				ability: "Insomnia",
				item: "Leftovers",
				shiny: true,
				moves: ["Defog", "Roost", "Night Shade"],
				signatureMove: "Toxic",
				evs: {
					hp: 248,
					spd: 252,
					def: 8,
				},
				nature: "Calm",
			},
			"Tauros": {
				species: "Tauros",
				ability: "Sheer Force",
				item: "Life Orb",
				moves: ["Zen Headbutt", "Iron Head", "Rock Slide"],
				signatureMove: "Body Slam",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Haunter": {
				species: "Haunter",
				ability: "Levitate",
				item: "Choice Scarf",
				moves: ["Shadow Ball", "Sludge Bomb", "Trick"],
				signatureMove: "Destiny Bond",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Staraptor": {
				species: "Staraptor",
				ability: "Reckless",
				item: "Choice Band",
				moves: ["Double-Edge", "Close Combat", "U-Turn"],
				signatureMove: "Brave Bird",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Aipom": {
				species: "Aipom",
				ability: "Skill Link",
				item: "Life Orb",
				moves: ["Fury Swipes", "Knock Off", "Brick Break"],
				signatureMove: "Fake Out",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Floatzel": {
				species: "Floatzel",
				ability: "Water Veil",
				item: "Choice Band",
				moves: ["Waterfall", "Ice Punch", "Aqua Jet"],
				signatureMove: "Pursuit",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Swellow": {
				species: "Swellow",
				ability: "Guts",
				item: "Flame Orb",
				moves: ["Brave Bird", "Return", "U-Turn"],
				signatureMove: "Protect",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Crawdaunt": {
				species: "Crawdaunt",
				ability: "Adaptability",
				item: "Focus Sash",
				moves: ["Knock Off", "Aqua Jet", "Dragon Dance"],
				signatureMove: "Crabhammer",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Serperior": {
				species: "Serperior",
				ability: "Contrary",
				item: "Life Orb",
				moves: ["Leaf Storm", "Giga Drain", "Glare"],
				signatureMove: "Dragon Pulse",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Samurott": {
				species: "Samurott",
				ability: "Shell Armor",
				item: "Leftovers",
				moves: ["Waterfall", "Knock Off", "Swords Dance"],
				signatureMove: "Aqua Jet",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Emboar": {
				species: "Emboar",
				ability: "Reckless",
				item: "Life Orb",
				moves: ["Flare Blitz", "Sucker Punch", "Wild Charge"],
				signatureMove: "Head Smash",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Gliscor": {
				species: "Gliscor",
				ability: "Poison Heal",
				item: "Toxic Orb",
				moves: ["Earthquake", "Toxic", "Roost"],
				signatureMove: "Protect",
				evs: {
					hp: 252,
					def: 252,
					spd: 4,
				},
				nature: "Impish",
			},
			"Talonflame": {
				species: "Talonflame",
				ability: "Gale Wings",
				moves: ["Acrobatics", "Roost", "Swords Dance"],
				signatureMove: "Will-O-Wisp",
				evs: {
					atk: 252,
					hp: 152,
					def: 78,
					spd: 28,
				},
				nature: "Adamant",
			},
			"Sceptile": {
				species: "Sceptile",
				ability: "Overgrow",
				item: "Life Orb",
				moves: ["Leaf Storm", "Hidden Power Ice", "Focus Blast"],
				signatureMove: "Giga Drain",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Glalie": {
				species: "Glalie",
				ability: "Ice Body",
				item: "Focus Sash",
				moves: ["Freeze-Dry", "Spikes", "Earthquake"],
				signatureMove: "Explosion",
				evs: {
					atk: 252,
					spe: 252,
					spa: 4,
				},
				nature: "Naive",
			},
			"Greninja": {
				species: "Greninja",
				ability: "Battle Bond",
				item: "Life Orb",
				moves: ["Scald", "Water Shuriken", "Ice Beam"],
				signatureMove: "Dark Pulse",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Donphan": {
				species: "Donphan",
				ability: "Sturdy",
				item: "Leftovers",
				moves: ["Earthquake", "Stealth Rock", "Rapid Spin"],
				signatureMove: "Ice Shard",
				evs: {
					hp: 252,
					def: 252,
					atk: 4,
				},
				nature: "Impish",
			},
			"Infernape": {
				species: "Infernape",
				ability: "Iron Fist",
				item: "Life Orb",
				moves: ["Flare Blitz", "Close Combat", "U-Turn"],
				signatureMove: "Mach Punch",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Feraligatr": {
				species: "Feraligatr",
				ability: "Sheer Force",
				item: "Life Orb",
				moves: ["Dragon Dance", "Waterfall", "Ice Punch"],
				signatureMove: "Aqua Jet",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Typhlosion": {
				species: "Typhlosion",
				ability: "Flash Fire",
				item: "Choice Scarf",
				moves: ["Eruption", "Flamethrower", "Extrasensory"],
				signatureMove: "Hidden Power Grass",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Housekeeper": {
				species: "Mr. Mime",
				ability: "Filter",
				item: "Choice Scarf",
				moves: ["Psychic", "Dazzling Gleam", "Trick"],
				signatureMove: "Thunderbolt",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Lapras": {
				species: "Lapras",
				ability: "Water Absorb",
				item: "Leftovers",
				moves: ["Waterfall", "Dragon Dance", "Ice Shard"],
				signatureMove: "Drill Run",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Adamant",
			},
			"Heracross": {
				species: "Heracross",
				ability: "Moxie",
				item: "Choice Scarf",
				moves: ["Close Combat", "Earthquake", "Knock Off"],
				signatureMove: "Megahorn",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Torkoal": {
				species: "Torkoal",
				ability: "Drought",
				item: "Leftovers",
				moves: ["Stealth Rock", "Lava Plume", "Toxic"],
				signatureMove: "Rapid Spin",
				evs: {
					hp: 248,
					def: 252,
					spa: 8,
				},
				nature: "Relaxed",
			},
			"Torterra": {
				species: "Torterra",
				ability: "Overgrow",
				item: "Leftovers",
				moves: ["Rock Polish", "Wood Hammer", "Stone Edge"],
				signatureMove: "Earthquake",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Garchomp": {
				species: "Garchomp",
				ability: "Rough Skin",
				item: "Rocky Helmet",
				moves: ["Earthquake", "Swords Dance", "Stealth Rock"],
				signatureMove: "Outrage",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Unfezant": {
				species: "Unfezant",
				ability: "Super Luck",
				item: "Life Orb",
				gender: "F",
				moves: ["Night Slash", "Return", "U-Turn"],
				signatureMove: "Quick Attack",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Noivern": {
				species: "Noivern",
				ability: "Infiltrator",
				item: "Life Orb",
				moves: ["Draco Meteor", "Flamethrower", "Hurricane"],
				signatureMove: "Focus Blast",
				evs: {
					spa: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Timid",
			},
			"Goodra": {
				species: "Goodra",
				ability: "Gooey",
				item: "Assault Vest",
				moves: ["Draco Meteor", "Sludge Wave", "Thunderbolt"],
				signatureMove: "Ice Beam",
				evs: {
					spa: 252,
					hp: 252,
					spd: 4,
				},
				nature: "Modest",
			},
			"Hawlucha": {
				species: "Hawlucha",
				ability: "Unburden",
				item: "Sitrus Berry",
				moves: ["Acrobatics", "High Jump Kick", "Swords Dance"],
				signatureMove: "Substitute",
				evs: {
					atk: 244,
					spe: 252,
					hp: 16,
				},
				nature: "Jolly",
			},
			"Tyranitar": {
				species: "Tyranitar",
				ability: "Sand Stream",
				item: "Leftovers",
				moves: ["Crunch", "Stone Edge", "Dragon Dance"],
				signatureMove: "Stealth Rock",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Adamant",
			},
			"Raticate": {
				species: "Raticate",
				ability: "Guts",
				item: "Flame Orb",
				moves: ["Quick Attack", "Sucker Punch", "Protect"],
				signatureMove: "Facade",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Beedrill": {
				species: "Beedrill",
				ability: "Swarm",
				item: "Focus Sash",
				moves: ["Fell Stinger", "Knock Off", "Drillrun"],
				signatureMove: "Poison Jab",
				evs: {
					atk: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Jolly",
			},
			"Krookodile": {
				species: "Krookodile",
				ability: "Moxie",
				item: "Choice Scarf",
				moves: ["Earthquake", "Stone Edge", "Crunch"],
				signatureMove: "Knock Off",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Gigalith": {
				species: "Gigalith",
				ability: "Sand Stream",
				item: "Assault Vest",
				moves: ["Return", "Earthquake", "Iron Head"],
				signatureMove: "Stone Edge",
				evs: {
					def: 252,
					hp: 252,
					atk: 4,
				},
				nature: "Impish",
			},
			"Seismitoad": {
				species: "Seismitoad",
				ability: "Water Absorb",
				item: "Leftovers",
				moves: ["Scald", "Earth Power", "Ice Beam"],
				signatureMove: "Sludge Wave",
				evs: {
					spa: 252,
					hp: 252,
					spd: 4,
				},
				nature: "Modest",
			},
			"Leavanny": {
				species: "Leavanny",
				ability: "Swarm",
				item: "Focus Sash",
				moves: ["Fell Stinger", "Knock Off", "Leaf Blade"],
				signatureMove: "Sticky Web",
				evs: {
					atk: 252,
					spe: 252,
					hp: 4,
				},
				nature: "Jolly",
			},
			"Decidueye": {
				species: "Decidueye",
				ability: "Long Reach",
				item: "Decidium Z",
				moves: ["Sucker Punch", "Leaf Blade", "Roost"],
				signatureMove: "Spirit Shackle",
				evs: {
					atk: 252,
					hp: 252,
					def: 4,
				},
				nature: "Adamant",
			},
			"Incineroar": {
				species: "Incineroar",
				ability: "Intimidate",
				item: "Incinium Z",
				moves: ["Fake Out", "Flare Blitz", "U-Turn"],
				signatureMove: "Darkest Lariat",
				evs: {
					atk: 252,
					hp: 252,
					spd: 4,
				},
				nature: "Adamant",
			},
			"Lycanroc": {
				species: "Lycanroc-Dusk",
				ability: "Tough Claws",
				item: "Life Orb",
				moves: ["Swords Dance", "Stone Edge", "Sucker Punch"],
				signatureMove: "Accelerock",
				evs: {
					atk: 252,
					spe: 252,
					def: 4,
				},
				nature: "Jolly",
			},
			"Naganadel": {
				species: "Naganadel",
				ability: "Beast Boost",
				item: "Dragonium Z",
				moves: ["Draco Meteor", "Fire Blast", "Nasty Plot"],
				signatureMove: "Sludge Wave",
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: "Timid",
			},
		};
		// convert moves to ids.
		for (let k in sets) {
			sets[k].moves = sets[k].moves.map(toId);
			sets[k].baseSignatureMove = toId(sets[k].baseSignatureMove);
		}

		// Generate the team randomly.
		let pool = this.shuffle(Object.keys(sets));
		for (let i = 0; i < 6; i++) {
			let set = sets[pool[i]];
			set.level = 100;
			set.name = pool[i];
			if (!set.ivs) {
				set.ivs = {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31};
			} else {
				for (let iv in {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31}) {
					set.ivs[iv] = set.ivs[iv] || set.ivs[iv] === 0 ? set.ivs[iv] : 31;
				}
			}
			// Assuming the hardcoded set evs are all legal.
			if (!set.evs) set.evs = {hp: 84, atk: 84, def: 84, spa: 84, spd: 84, spe: 84};
			set.moves = [this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves)].concat(set.signatureMove);
			team.push(set);
		}
		return team;
	}
}

module.exports = RandomAshTeams;
