'use strict';

const RandomTeams = require('../../data/random-teams');

class RandomTMSTeams extends RandomTeams {
	randomTMSTeam() {
		let team = [];
		let sets = {
			'Rachel': {
				species: 'Cherrim-Sunshine',
				ability: 'Protean',
				gender: 'F',
				item: 'Power Herb',
				moves: ['steameruption', 'iceburn', 'hurricane', 'paleowave', 'earthpower', 'gigadrain', 'icebeam', 'sludgebomb', 'blueflare', 'hypervoice', 'moonblast', 'psystrike', 'nightdaze', 'bugbuzz', 'secretsword', 'shadowball', 'flashcannon', 'dragonpulse'],
				signatureMove: 'Solar Beam',
				evs: {
					spa: 252,
					spd: 8,
					hp: 248,
					spe: 252,
				},
				nature: 'Modest',
			},
			'Mewth (1)': {
				species: 'Furret',
				ability: 'Prankster',
				gender: 'F',
				item: 'Lum Berry',
				moves: ['nightmare', 'leechseed', 'recover'],
				signatureMove: 'Spore',
				evs: {
					def: 252,
					spd: 8,
					hp: 248,
				},
				nature: 'Bold',
			},
			'Stella': {
				species: 'Meowstic-F',
				ability: 'Fur Coat',
				shiny: 'Yes',
				item: 'Assault Vest',
				moves: ['judgment', 'blueflare', 'oblivionwing', 'psychic', 'shadowball', 'gigadrain', 'chargebeam'],
				signatureMove: 'Psystrike',
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: 'Timid',
			},
			'Nathan': {
				species: 'Manectric-Mega',
				ability: 'Contrary',
				gender: 'M',
				shiny: 'Yes',
				item: 'Choice Specs',
				moves: ['dracometeor', 'overheat', 'leafstorm'],
				signatureMove: 'Volt Switch',
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: 'Timid',
			},
			'Achim': {
				species: 'Magmortar',
				ability: 'Adaptability',
				gender: 'M',
				item: 'Heat Rock',
				moves: ['fireblast', 'solarbeam', 'thunderbolt', 'icebeam', 'agility'],
				signatureMove: 'Sunny Day',
				evs: {
					hp: 252,
					atk: 252,
					def: 252,
					spa: 252,
					spd: 252,
					spe: 252,
				},
				nature: 'Modest',
			},
			'Alkeides': {
				species: 'Rayquaza',
				ability: 'Air Lock',
				gender: 'M',
				item: 'Life Orb',
				moves: ['aerialace', 'dragondance', 'dragontail', 'earthquake', 'stoneedge', 'rest', 'sleeptalk', 'zapcannon', 'gravity'],
				signatureMove: 'Dragon Claw',
				evs: {
					atk: 252,
					spe: 252,
					spa: 4,
				},
				nature: 'Lonely',
			},
			'Varnava': {
				species: 'Zygarde',
				ability: 'Protean',
				gender: 'M',
				item: 'Leftovers',
				moves: ['boltstrike', 'flareblitz', 'outrage', 'woodhammer', 'iciclecrash', 'playrough', 'crabhammer', 'foulplay'],
				signatureMove: 'Thousand Arrows',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Tatu': {
				species: 'Tornadus-Therian',
				ability: 'Delta Stream',
				gender: 'M',
				item: 'Flying Gem',
				moves: ['hurricane', 'recover', 'spore', 'fireblast', 'boomburst', 'icebeam', 'energyball'],
				signatureMove: 'Oblivion Wing',
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: 'Timid',
			},
			'Ursula': {
				species: 'Diancie-Mega',
				ability: 'Protean',
				gender: 'F',
				Shiny: 'Yes',
				item: 'Fairium Z',
				moves: ['originpulse', 'hurricane', 'paleowave', 'geomancy', 'flashcannon', 'darkpulse', 'fireblast', 'thunderbolt', 'sludgebomb', 'psychic', 'psystrike', 'hypervoice', 'shadowball', 'bugbuzz', 'earthpower', 'icebeam', 'aurasphere', 'dragonpulse'],
				signatureMove: 'Moonblast',
				evs: {
					spa: 252,
					spe: 252,
					spd: 4,
				},
				nature: 'Timid',
			},
			'Jaydon': {
				species: 'Diggersby',
				ability: 'Iron Fist',
				gender: 'M',
				item: 'Choice Band',
				moves: ['firepunch', 'icepunch', 'thunderpunch', 'drainpunch', 'poweruppunch', 'cometpunch', 'bulletpunch', 'machpunch', 'dizzypunch', 'shadowpunch', 'suckerpunch'],
				signatureMove: 'Mega Punch',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Korrina': {
				species: 'Lucario',
				ability: 'Steadfast',
				gender: 'F',
				item: 'Lucarionite',
				moves: ['flashcannon', 'aurasphere', 'closecombat', 'darkpulse', 'knockoff', 'ironhead'],
				signatureMove: 'Shell Smash',
				evs: {
					spa: 252,
					spe: 252,
					atk: 4,
				},
				nature: 'Mild',
			},
			'Gholam': {
				species: 'Groudon',
				ability: 'Drought',
				gender: 'M',
				item: 'Red Orb',
				moves: ['poweruppunch', 'sacredfire', 'petalblizzard'],
				signatureMove: 'Precipice Blades',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Stevo': {
				species: 'Heracross-Mega',
				ability: 'Moxie',
				gender: 'M',
				item: 'Leftovers',
				moves: ['closecombat', 'pursuit', 'substitute', 'hornleech', 'spore'],
				signatureMove: 'Megahorn',
				evs: {
					hp: 248,
					atk: 252,
					spd: 8,
				},
				nature: 'Adamant',
			},
			'Truthlon': {
				species: 'Kyurem-White',
				ability: 'Snow Warning',
				gender: 'M',
				item: 'Choice Scarf',
				moves: ['dragonpulse', 'boomburst', 'fusionflare', 'hurricane'],
				signatureMove: 'Blizzard',
				evs: {
					hp: 252,
					spe: 252,
					spd: 252,
					spa: 252,
					def: 252,
				},
				nature: 'Timid',
			},
			'Alkeides Mega': {
				species: 'Rayquaza-Mega',
				ability: 'Beast Boost',
				gender: 'M',
				item: 'Enigma Berry',
				moves: ['dragonascent', 'firelash', 'dragonclaw', 'extremespeed', 'reflecttype', 'closecombat', 'playrough'],
				signatureMove: 'King\'s Shield',
				evs: {
					spe: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Jolly',
			},
			'Volya': {
				species: 'Lunala',
				ability: 'Shadow Shield',
				gender: 'F',
				shiny: 'Yes',
				item: 'Leftovers',
				moves: ['psystrike', 'shadowball', 'psychic', 'recover', 'synthesis', 'roost', 'moonblast'],
				signatureMove: 'Moongeist Beam',
				evs: {
					hp: 252,
					spd: 252,
					spa: 4,
				},
				nature: 'Calm',
			},
			'Volgeo': {
				species: 'Solgaleo',
				ability: 'Chlorophyll',
				gender: 'M',
				shiny: 'Yes',
				item: 'Leftovers',
				moves: ['solarblade', 'morningsun', 'sunnyday', 'psychicfangs', 'growth', 'grassyterrain', 'flareblitz', 'accelerock'],
				signatureMove: 'Sunsteel Strike',
				evs: {
					spe: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Brett': {
				species: 'Charjabug',
				ability: 'Wonder Guard',
				gender: 'M',
				item: 'Normalium Z',
				moves: ['thunder', 'pollenpuff', 'recover'],
				signatureMove: 'Metronome',
				evs: {
					hp: 252,
					def: 252,
					spa: 4,
				},
				nature: 'Bold',
			},
			'Lincoln': {
				species: 'Magikarp',
				ability: 'Wonder Guard',
				gender: 'M',
				shiny: 'Yes',
				item: 'Leftovers',
				moves: ['originpulse', 'swordsdance', 'tailglow', 'kingsshield', 'gigadrain', 'petalblizzard', 'firelash', 'heatwave'],
				signatureMove: 'Magikarp\'s Revenge',
				evs: {
					spa: 500,
					atk: 500,
					spe: 252,
				},
				nature: 'Naive',
			},
			'Plasmane': {
				species: 'Rotom',
				ability: 'Protean',
				gender: 'M',
				item: 'Leftovers',
				moves: ['thunder', 'recover', 'protect', 'hydropump', 'hurricane', 'gigadrain', 'fireblast', 'icebeam'],
				signatureMove: 'Moongeist Beam',
				evs: {
					hp: 252,
					spa: 252,
					spd: 4,
				},
				nature: 'Modest',
			},
			'Ashley': {
				species: 'Mimikyu',
				ability: 'Disguise',
				gender: 'F',
				item: 'Normalium Z',
				moves: ['shadowsneak', 'splash', 'shadowclaw', 'recover', 'suckerpunch', 'kingsshield'],
				signatureMove: 'playrough',
				evs: {
					hp: 4,
					atk: 252,
					spe: 252,
				},
				nature: 'Hasty',
			},
			'Varnava Complete': {
				species: 'Zygarde-Complete',
				ability: 'Comatose',
				gender: 'M',
				item: 'Life Orb',
				moves: ['coil', 'outrage', 'icehammer', 'crabhammer', 'recover', 'dragondance'],
				signatureMove: 'Thousand Arrows',
				evs: {
					hp: 252,
					def: 252,
					spd: 252,
				},
				nature: 'Careful',
			},
			'Andrew': {
				species: 'Yveltal',
				ability: 'Shadow Shield',
				gender: 'M',
				item: 'Lum Berry',
				moves: ['roost', 'darkpulse', 'shadowball', 'hurricane', 'substitute', 'spore'],
				signatureMove: 'Oblivion Wing',
				evs: {
					hp: 252,
					spe: 252,
					spd: 252,
					spa: 4,
				},
				nature: 'Calm',
			},
			'Ideals': {
				species: 'Zekrom',
				ability: 'Gluttony',
				gender: 'M',
				item: 'Starf Berry',
				moves: ['bravebird', 'dragonclaw', 'zenheadbutt', 'ironhead', 'earthquake', 'waterfall', 'recycle', 'crunch', 'outrage'],
				signatureMove: 'Fusion Bolt',
				evs: {
					hp: 252,
					atk: 252,
					def: 4,
				},
				nature: 'Naughty',
			},
			'Truth': {
				species: 'Reshiram',
				ability: 'Gluttony',
				gender: 'M',
				item: 'Starf Berry',
				moves: ['hurricane', 'dracometeor', 'psychic', 'doomdesire', 'earthpower', 'hydropump', 'recycle', 'nightdaze', 'dragonpulse'],
				signatureMove: 'Fusion Flare',
				evs: {
					hp: 248,
					spa: 252,
					spd: 8,
				},
				nature: 'Mild',
			},
			'Poncho': {
				species: 'Wobbuffet',
				ability: 'Unaware',
				gender: 'M',
				item: 'Leftovers',
				moves: ['counter', 'cosmicpower', 'taunt', 'torment', 'encore', 'substitute', 'recover', 'healbell', 'trickroom'],
				signatureMove: 'Mirror Coat',
				evs: {
					hp: 252,
					spd: 252,
					def: 252,
				},
				nature: 'Calm',
			},
			'Ceasar': {
				species: 'Gallade',
				ability: 'Ceasars Wish',
				gender: 'M',
				item: 'Aguav Berry',
				moves: ['kingsshield', 'psychocut', 'sacredsword', 'dragondance', 'powertrip', 'knockoff', 'suckerpunch', 'shadowsneak', 'playrough'],
				signatureMove: 'Close Combat',
				evs: {
					hp: 252,
					atk: 248,
					spe: 8,
				},
				nature: 'Adamant',
			},
			'Liochant': {
				species: 'Araquanid',
				ability: 'Water Bubble',
				gender: 'M',
				item: 'Leftovers',
				moves: ['dragondance', 'stickyweb', 'toxicthread', 'defendorder', 'attackorder', 'leechlife', 'healorder', 'venomdrench'],
				signatureMove: 'Crabhammer',
				evs: {
					hp: 100,
					def: 252,
					spe: 4,
					atk: 152,
				},
				nature: 'Impish',
			},
			'Ghator': {
				species: 'Necrozma',
				ability: 'Moody',
				gender: 'M',
				item: 'Leftovers',
				moves: ['psychic', 'recover', 'bugbuzz', 'gigadrain', 'meanlook', 'perishsong', 'psystrike'],
				signatureMove: 'Spiky Shield',
				evs: {
					hp: 252,
					spd: 252,
					def: 252,
					spa: 4,
				},
				nature: 'Sassy',
			},
			'Ashten': {
				species: 'Pikachu',
				ability: 'Levitate',
				gender: 'M',
				item: 'Light Ball',
				moves: ['shiftgear', 'iciclecrash', 'dig'],
				signatureMove: 'Bolt Strike',
				evs: {
					spe: 252,
					atk: 252,
					hp: 4,
				},
				nature: 'Jolly',
			},
			'Temporal': {
				species: 'Dialga',
				ability: 'Dark Aura',
				gender: 'M',
				item: 'Adamant Orb',
				moves: ['flashcannon', 'darkpulse', 'bugbuzz'],
				signatureMove: 'Roar of Time',
				evs: {
					hp: 252,
					spa: 252,
					def: 4,
				},
				nature: 'Rash',
			},
			'Spacial': {
				species: 'Palkia',
				ability: 'Fairy Aura',
				gender: 'M',
				item: 'Lustrous Orb',
				moves: ['steameruption', 'moonblast', 'thunderbolt'],
				signatureMove: 'Spacial Rend',
				evs: {
					hp: 252,
					spa: 252,
					spd: 4,
				},
				nature: 'Modest',
			},
			'Abyssal': {
				species: 'Giratina',
				ability: 'Prankster',
				gender: 'M',
				item: 'Leftovers',
				moves: ['reflect', 'lightscreen', 'toxic', 'willowisp', 'thunderwave', 'refresh', 'recover', 'dragontail'],
				signatureMove: 'Shadow Force',
				evs: {
					hp: 252,
					spd: 252,
					atk: 4,
				},
				nature: 'Careful',
			},
			'Abyssal-Origin': {
				species: 'Giratina-Origin',
				ability: 'Beast Boost',
				gender: 'M',
				item: 'Griseous Orb',
				moves: ['outrage', 'shadowsneak', 'bulkup', 'wildcharge', 'hornleech', 'dragonclaw'],
				signatureMove: 'Shadow Force',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Brett 2': {
				species: 'Vikavolt',
				ability: 'Levitate',
				gender: 'M',
				item: 'Normalium Z',
				moves: ['pollenpuff', 'thunder', 'agility'],
				signatureMove: 'Metronome',
				evs: {
					hp: 252,
					def: 252,
					spa: 252,
					spe: 252,
				},
				nature: 'Bold',
			},
			'Spike': {
				species: 'Scrafty',
				ability: 'Moxie',
				gender: 'M',
				item: 'Leftovers',
				moves: ['crunch', 'suckerpunch', 'swagger', 'spectralthief', 'slackoff', 'bulkup', 'dragondance'],
				signatureMove: 'Drain Punch',
				evs: {
					hp: 252,
					atk: 252,
					spd: 252,
					def: 252,
				},
				nature: 'Adamant',
			},
			'Roger': {
				species: 'Bidoof-God',
				ability: 'Assisting Finger',
				gender: 'M',
				item: 'Leftovers',
				moves: ['swordsdance', 'aquatail', 'drainpunch', 'shadowclaw', 'crunch', 'stockpile', 'recover'],
				signatureMove: 'Return',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Gholam': {
				species: 'Groudon',
				ability: 'Drought',
				gender: 'M',
				item: 'Red Orb',
				moves: ['poweruppunch', 'sacredfire', 'petalblizzard'],
				signatureMove: 'Precipice Blades',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Darlene': {
				species: 'Floette-Eternal',
				ability: 'Rock Head',
				gender: 'F',
				item: 'Power Herb',
				moves: ['lightofruin', 'moonblast', 'darkpulse', 'leechseed', 'strengthsap', 'gigadrain', 'irondefense'],
				signatureMove: 'Geomancy',
				evs: {
					hp: 252,
					spd: 252,
					spa: 4,
				},
				nature: 'Gentle',
			},
			'Prodigy': {
				species: 'Wigglytuff',
				ability: 'Serene Grace',
				gender: 'M',
				item: 'Leftovers',
				moves: ['cosmicpower', 'moonblast', 'shadowball', 'lavaplume', 'softboiled'],
				signatureMove: 'Tri Attack',
				evs: {
					hp: 252,
					def: 252,
					spd: 252,
					spa: 252,
				},
				nature: 'Modest',
			},
			'Anakledos': {
				species: 'Druddigon',
				ability: 'Moxie',
				gender: 'M',
				item: 'Leftovers',
				moves: ['dragondance', 'crunch', 'closecombat', 'sacredfire', 'shadowclaw', 'stoneedge', 'earthquake', 'slackoff'],
				signatureMove: 'Dragon Claw',
				evs: {
					spe: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Jolly',
			},
			'Rylan': {
				species: 'Drapion',
				ability: 'Super Luck',
				gender: 'M',
				item: 'Scope Lens',
				moves: ['nightslash', 'slash', 'crabhammer', 'psychocut', 'shadowclaw', 'banefulbunker', 'dragondance'],
				signatureMove: 'Cross Poison',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
				},
				nature: 'Adamant',
			},
			'Aaron': {
				species: 'Glalie-Mega',
				ability: 'Ice Body',
				gender: 'M',
				item: 'Leftovers',
				moves: ['auroraveil', 'shadowball', 'surf', 'hail', 'flashcannon', 'recover'],
				signatureMove: 'Ice Beam',
				evs: {
					hp: 252,
					spd: 252,
					spa: 252,
					def: 252,
				},
				nature: 'Modest',
			},
			'Glitch': {
				species: 'Porygon-Z',
				ability: 'Adaptability',
				gender: 'M',
				item: 'Normalium Z',
				moves: ['moongeistbeam', 'boomburst', 'icebeam', 'psychic', 'airslash', 'teeterdance', 'hypnosis'],
				signatureMove: 'Conversion',
				evs: {
					hp: 252,
					spa: 252,
					spe: 252,
				},
				nature: 'Modest',
			},
			'Lincoln 2': {
				species: 'Gyarados-Mega',
				ability: 'Download',
				gender: 'M',
				item: 'Leppa Berry',
				moves: ['originpulse', 'swordsdance', 'tailglow', 'kingsshield', 'gigadrain', 'petalblizzard', 'firelash', 'heatwave'],
				signatureMove: 'Oceanic Operetta',
				evs: {
					hp: 252,
					atk: 252,
					spd: 4,
					spe: 252,
				},
				nature: 'Adamant',
			},
			'Lon': {
				species: 'Kyurem',
				ability: 'Beast Boost',
				gender: 'M',
				item: 'Leftovers',
				moves: ['stoneedge', 'dragonclaw', 'zenheadbutt', 'recover', 'crunch', 'suckerpunch'],
				signatureMove: 'Icicle Crash',
				evs: {
					hp: 252,
					atk: 252,
					spe: 252,
				},
				nature: 'Jolly',
			},
			'Mewth 2': {
				species: 'Furret',
				ability: 'Bad Dreams',
				gender: 'F',
				item: 'Leftovers',
				moves: ['spore', 'nightmare', 'cosmicpower'],
				signatureMove: 'Oblivion Banisher',
				evs: {
					hp: 252,
					def: 252,
					spd: 252,
					spe: 252,
				},
				nature: 'Jolly',
			},
		};
		// convert moves to ids.
		for (let k in sets) {
			sets[k].moves = sets[k].moves.map(toId);
			sets[k].baseSignatureMove = toId(sets[k].baseSignatureMove);
		}

		// Generate the team randomly.
		let pool = Dex.shuffle(Object.keys(sets));
		for (let i = 0; i < 6; i++) {
			let set = sets[pool[i]];
			set.level = 100;
			set.name = pool[i];
			if (!set.ivs) {
				set.ivs = {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31};
			} else {
				for (let iv in {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31}) {
					set.ivs[iv] = set.ivs[iv] || set.ivs[iv] === 0 ? set.ivs[iv] : 31;
				}
			}
			// Assuming the hardcoded set evs are all legal.
			if (!set.evs) set.evs = {hp: 84, atk: 84, def: 84, spa: 84, spd: 84, spe: 84};
			set.moves = [this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves)].concat(set.signatureMove);
			team.push(set);
		}
		return team;
	}
}

module.exports = RandomTMSTeams;
