'use strict';

exports.BattleLearnsets = {
	solgaleo: {
		learnset: {
			inherit: true,
			spacialstrike: ["7L1"],
			pitfall: ["7L14"],
			supernovaslash: ["7L23"],
			steampunkslam: ["7L35"],
			meteormash: ["7L57"],
			celestialbreak: ["7M"],
		},
	},
	lunala: {
		learnset: {
			inherit: true,
			asteroidpulse: ["7L1"],
			prismaticlaser: ["7L24"],
			eclipseforce: ["7L45"],
			nebulablast: ["7L67"],
		},
	},
	necrozma: {
		learnset: {
			inherit: true,
			asteroidpulse: ["7L1"],
			spacialstrike: ["7L4"],
			pitfall: ["7L14"],
			cosmicpower: ["7L16"],
			supernovaslash: ["7L22"],
			prismaticlaser: ["7L24"],
			celestialbreak: ["7M"],
		},
	},
	clefable: {
		learnset: {
			inherit: true,
			prismaticlaser: ["7L26"],
			spacialstrike: ["7L32"],
			nebulablast: ["7L43"],
		},
	},
	beheeyem: {
		learnset: {
			inherit: true,
			magicalpunch: ["7L3"],
			blindingbeam: ["7L13"],
			prismaticlaser: ["7L23"],
			asteroidpulse: ["7L35"],
			nebulablast: ["7L54"],
			moonblast: ["7L67"],
		},
	},
	cresselia: {
		learnset: {
			inherit: true,
			asteroidpulse: ["7L23"],
			blindingbeam: ["7L45"],
		},
	},
	growlithe: {
		learnset: {
			inherit: true,
			growl: ["7L1"],
			galacticfang: ["7M"],
		},
	},
	arcanine: {
		learnset: {
			inherit: true,
			growl: ["7L1"],
			galacticfang: ["7M"],
		},
	},
	pikachu: {
		learnset: {
			inherit: true,
			tailglow: ["7L100"],
		},
	},
	raichu: {
		learnset: {
			inherit: true,
			electrohavoc: ["7L82"],
			tailglow: ["7L100"],
		},
	},
	golduck: {
		learnset: {
			inherit: true,
			aurasphere: ["7L45"],
			dazzlinggleam: ["7M"],
		},
	},
	milotic: {
		learnset: {
			inherit: true,
			moonblast: ["7L54"],
		},
	},
	flygon: {
		learnset: {
			inherit: true,
			leechlife: ["7M"],
			xscissor: ["7M"],
		},
	},
	audino: {
		learnset: {
			inherit: true,
			moonblast: ["7L67"],
		},
	},
	blastoise: {
		learnset: {
			inherit: true,
			asteroidpulse: ["7L1", "7M"],
			shellsmash: ["7L66"],
		},
	},
	accelgor: {
		learnset: {
			inherit: true,
			aurasphere: ["7L1"],
			quiverdance: ["7L46"],
		},
	},
	luxray: {
		learnset: {
			inherit: true,
			galacticfang: ["7L23"],
			powercooldown: ["7L65"],
		},
	},
	mismagius: {
		learnset: {
			inherit: true,
			moonblast: ["7L43"],
		},
	},
	sceptile: {
		learnset: {
			inherit: true,
			dracometeor: ["7T"],
			seedflare: ["7L87"],
		},
	},
	aerodactyl: {
		learnset: {
			inherit: true,
			bravebird: ["7L47"],
			galacticfang: ["7L23"],
		},
	},
	armaldo: {
		learnset: {
			inherit: true,
			galacticfang: ["7L20"],
			shellsmash: ["7L58"],
			steampunkslam: ["7L44"],
		},
	},
	torkoal: {
		learnset: {
			inherit: true,
			cosmicpower: ["7M"],
			shelltrap: ["7L48"],
		},
	},
	arbok: {
		learnset: {
			inherit: true,
			galacticfang: ["7L1"],
		},
	},
	seviper: {
		learnset: {
			inherit: true,
			galacticfang: ["7L1"],
		},
	},
	zangoose: {
		learnset: {
			inherit: true,
			magicalpunch: ["7L11"],
		},
	},
	weezing: {
		learnset: {
			inherit: true,
			cosmicpower: ["7M"],
			recover: ["7L34"],
		},
	},
	sunflora: {
		learnset: {
			inherit: true,
			fireblast: ["7M"],
			flamethrower: ["7M"],
		},
	},
	furret: {
		learnset: {
			inherit: true,
			curse: ["7L1"],
			phantomforce: ["7L24"],
		},
	},
	feraligatr: {
		learnset: {
			inherit: true,
			dracometeor: ["7T"],
			dragonpulse: ["7L23"],
		},
	},
	dhelmise: {
		learnset: {
			inherit: true,
			ironhead: ["7L32"],
			meteormash: ["7L25"],
			steampunkslam: ["7L52"],
		},
	},
	ursaring: {
		learnset: {
			inherit: true,
			machpunch: ["7L1"],
			outrage: ["7L43"],
			playrough: ["7L24"],
			suckerpunch: ["7L55"],
		},
	},
	electivire: {
		learnset: {
			inherit: true,
			closecombat: ["7L56"],
			drainpunch: ["6T"],
			extremespeed: ["7L65"],
		},
	},
	magmortar: {
		learnset: {
			inherit: true,
			boomburst: ["7L42"],
			electroball: ["7L12"],
			electrohavoc: ["7L22"],
			powercooldown: ["7L34"],
			thundershock: ["7L1"],
			zapcannon: ["7L43"],
			zingzap: ["7L17"],
		},
	},
	bellossom: {
		learnset: {
			inherit: true,
			spore: ["7L1"],
			mistyterrain: ["7L1"],
		},
	},
	avalugg: {
		learnset: {
			inherit: true,
			steampunkslam: ["7L33"],
		},
	},
	cherrim: {
		learnset: {
			inherit: true,
			ember: ["7L1"],
			fireblast: ["7M"],
			flamethrower: ["7M"],
		},
	},
	shedinja: {
		learnset: {
			inherit: true,
			curse: ["7L20"],
			phantomforce: ["7L44"],
		},
	},
	pachirisu: {
		learnset: {
			inherit: true,
			dazzlinggleam: ["7M"],
			drainingkiss: ["7L15"],
			galacticfang: ["7L22"],
			playrough: ["7L44"],
			recover: ["7L32"],
		},
	},
	florges: {
		learnset: {
			inherit: true,
			ingrain: ["7L23"],
			leafstorm: ["7L52"],
		},
	},
	eelektross: {
		learnset: {
			inherit: true,
			bugbite: ["7L1"],
			bugbuzz: ["7L47"],
			furycutter: ["7L5"],
			leechlife: ["7M"],
			strugglebug: ["7M"],
			quiverdance: ["7L56"],
		},
	},
	komala: {
		learnset: {
			inherit: true,
			drainpunch: ["7L45"],
			knockoff: ["L50"],
			slackoff: ["7L23"],
		},
	},
	chatot: {
		learnset: {
			inherit: true,
			disarmingvoice: ["7L1"],
		},
	},
	beautifly: {
		learnset: {
			inherit: true,
			drainingkiss: ["7L12"],
			moonblast: ["7L35"],
		},
	},
	galvantula: {
		learnset: {
			inherit: true,
			boomburst: ["7L43"],
		},
	},
	granbull: {
		learnset: {
			inherit: true,
			closecombat: ["7L56"],
			dracometeor: ["7T"],
			dragonclaw: ["7M"],
			dragondance: ["7L23"],
			magicalpunch: ["7L34"],
			pixiepunch: ["7L34"],
		},
	},
	noctowl: {
		learnset: {
			inherit: true,
			cosmicpower: ["7M"],
			shadowsneak: ["7L5"],
			spacialstrike: ["7L21"],
		},
	},
	carbink: {
		learnset: {
			inherit: true,
			cosmicpower: ["7M"],
			healbell: ["7L17"],
			rapidspin: ["7L32"],
			recover: ["7L40"],
		},
	},
	incineroar: {
		learnset: {
			inherit: true,
			knockoff: ["7L82"],
			magicalpunch: ["7L1"],
			suckerpunch: ["7L1"],
		},
	},
	abomasnow: {
		learnset: {
			inherit: true,
			iciclecrash: ["7L54"],
			magicalpunch: ["7L25"],
		},
	},
	hypno: {
		learnset: {
			inherit: true,
			aurasphere: ["7L51"],
			cosmicpower: ["7M"],
			moonblast: ["7L37"],
		},
	},
	smk: {
		learnset: {
			outrage: ["7L1", "7L60"],
			tackle: ["7L1"],
			bite: ["7L3"],
			crunch: ["7L15"],
			foulplay: ["7L29"],
			explosion: ["7M", "7L37"],
			agility: ["7L42"],
			selfdestruct: ["7L32"],
			headsmash: ["7L62"],
			astonish: ["7L5"],
			nightshade: ["7L17"],
			shadowpunch: ["7L15"],
			knockoff: ["7L29"],
			spectralthief: ["7L45"],
			endeavor: ["7L4"],
			headbutt: ["7L13"],
			doubleteam: ["7L49", "7M"],
			workup: ["7M"],
			calmmind: ["7M"],
			bulkup: ["7M"],
			sunnyday: ["7M"],
			taunt: ["7M"],
			protect: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			brickbreak: ["7M"],
			torment: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			snarl: ["7M"],
			confide: ["7M"],
			drinkbleach: ["7L70"],
		},
	},
	musteltank: {
		learnset: {
			poisonjab: ["7M"],
			ironhead: ["7L56"],
			earthquake: ["7M"],
			honeclaws: ["7M"],
			bulkup: ["7M"],
			dig: ["7M"],
			superpower: ["7L46"],
			irontail: ["7L24"],
			heavyslam: ["7L36"],
			protect: ["7M"],
			toxic: ["7M"],
			growl: ["7L1"],
			screech: ["7L6"],
			irondefense: ["7L26"],
			rollout: ["7L8"],
			banefulbunker: ["7L53"],
			rapidspin: ["7L42"],
			rest: ["7M"],
			sleeptalk: ["7M"],
			recycle: ["7L9"],
			poisongas: ["7L3"],
			metalsound: ["7L13"],
			metalclaw: ["7L21"],
			suckerpunch: ["7L29"],
			trickroom: ["7M"],
		},
	},
	pence: {
		learnset: {
			protect: ["7M"],
			drainpunch: ["7L45"],
			closecombat: ["7L57"],
			playrough: ["7L58"],
			suckerpunch: ["7L20"],
			knockoff: ["7L3"],
			tackle: ["7L1"],
			icepunch: ["7L13", "6T"],
			earthquake: ["7M"],
			superpower: ["7L45"],
			moonblast: ["7L33"],
			focusblast: ["7L59"],
			aurasphere: ["7L86"],
			swordsdance: ["7M"],
			takedown: ["7L10"],
			fairywind: ["7L12"],
			dazzlinggleam: ["7M"],
			karatechop: ["7L1"],
			strength: ["6M"],
			cut: ["6M"],
			rocksmash: ["7M", "6M"],
			doubleedge: ["7L46"],
			thunderpunch: ["7L13", "6T"],
			poisonjab: ["7M"],
			headsmash: ["7L55"],
			rockslide: ["7M"],
			stoneedge: ["7M"],
			hammerarm: ["7L12"],
			hiddenpower: ["7M"],
			bulkup: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			toxic: ["7M"],
		},
	},
	frioth: {
		learnset: {
			wideguard: ["7L1"],
			strugglebug: ["7L1"],
			aquaring: ["7L1"],
			powdersnow: ["7L8"],
			bugbite: ["7L10", "7E"],
			iceshard: ["7L16"],
			bugbuzz: ["7L22"],
			mirrorcoat: ["7L34"],
			hail: ["7L39", "7M"],
			quiverdance: ["7L45"],
			aurorabeam: ["7L48"],
			iciclecrash: ["7L51"],
			iciclespear: ["7L51"],
			blizzard: ["7L56", "7M"],
			swordsdance: ["7L63", "7M"],
			workup: ["7M"],
			calmmind: ["7M"],
			toxic: ["7M"],
			hiddenpower: ["7M"],
			taunt: ["7M"],
			icebeam: ["7M"],
			hyperbeam: ["7M"],
			lightscreen: ["7M"],
			protect: ["7M"],
			raindance: ["7M"],
			roost: ["7M"],
			safeguard: ["7M"],
			frustration: ["7M"],
			return: ["7M"],
			leechlife: ["7M"],
			doubleteam: ["7M"],
			reflect: ["7M"],
			aerialace: ["7M"],
			facade: ["7M"],
			rest: ["7M"],
			attract: ["7M"],
			thief: ["7M"],
			round: ["7M"],
			falseswipe: ["7M"],
			skydrop: ["7M"],
			quash: ["7M"],
			acrobatics: ["7M"],
			gigaimpact: ["7M"],
			auroraveil: ["7M"],
			fly: ["7M"],
			psychup: ["7M"],
			frostbreath: ["7M"],
			xscissor: ["7M"],
			infestation: ["7M"],
			swagger: ["7M"],
			sleeptalk: ["7M"],
			uturn: ["7M"],
			substitute: ["7M"],
			flashcannon: ["7M"],
			surf: ["7M"],
			naturepower: ["7M"],
			waterfall: ["7M"],
			dazzlinggleam: ["7M"],
			confide: ["7M"],
			acupressure: ["7E"],
			crosspoison: ["7E"],
			pinmissle: ["7E"],
			icehammer: ["7E"],
			spikecannon: ["7E"],
			spikes: ["7E"],
			snore: ["7T"],
			waterpulse: ["7T"],
			signalbeam: ["7T"],
			icepunch: ["7T"],
			knockoff: ["7T"],
			dualchop: ["7T"],
			endeavor: ["7T"],
			uproar: ["7T"],
			ironhead: ["7T"],
			aquatail: ["7T"],
			lastresort: ["7T"],
			hypervoice: ["7T"],
			skyattack: ["7T"],
			block: ["7T"],
			recycle: ["7T"],
			irondefense: ["7T"],
			tailwind: ["7T"],
			electroweb: ["7T"],
			icywind: ["7T"],
		},
	},
	octanko: {
		learnset: {
			attract: ["7M", "6M", "5M", "4M", "3M"],
			aurorabeam: ["7L14", "7L1", "6L1", "5L1", "4L1", "3L22"],
			bind: ["6T", "5T"],
			blizzard: ["7M", "6M", "5M", "4M", "3M"],
			bounce: ["6T", "5T", "4T"],
			brine: ["4M"],
			bubblebeam: ["7L18", "6L18", "5L19", "4L19", "3L22"],
			bulletseed: ["7L46", "6L46", "5L29", "4M", "4L29", "3M"],
			captivate: ["4M"],
			chargebeam: ["7M", "6M", "5M", "4M"],
			confide: ["7M", "6M"],
			constrict: ["7L6", "7L1", "6L1", "5L1", "4L1", "3L11"],
			defensecurl: ["3T"],
			dive: ["6M", "5M", "4T", "3M"],
			doubleedge: ["3T"],
			doubleteam: ["7M", "6M", "5M", "4M", "3M"],
			endure: ["4M", "3T"],
			energyball: ["7M", "6M", "5M", "4M"],
			facade: ["7M", "6M", "5M", "4M", "3M"],
			fireblast: ["7M", "6M", "5M", "4M", "3M"],
			flamethrower: ["7M", "6M", "5M", "4M", "3M"],
			flashcannon: ["7M", "6M", "5M", "4M"],
			focusenergy: ["7L22", "6L22", "5L23", "4L23", "3L38"],
			frustration: ["7M", "6M", "5M", "4M", "3M"],
			gigaimpact: ["7M", "6M", "5M", "4M"],
			gunkshot: ["7L1", "6T", "6L1", "5T", "5L1", "4T", "4L1"],
			hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
			hurricane: ["7L57"],
			hydropump: ["7L52", "6L52", "5L52"],
			hyperbeam: ["7M", "7L58", "6M", "6L58", "5M", "5L55", "4M", "4L55", "4S0", "3M", "3L70"],
			icebeam: ["7M", "7L40", "6M", "6L40", "5M", "5L48", "4M", "4L48", "4S0", "3M", "3L54"],
			icywind: ["6T", "5T", "4T"],
			incinerate: ["6M", "5M"],
			mimic: ["3T"],
			mudslap: ["4T", "3T"],
			naturalgift: ["4M"],
			octazooka: ["7L1", "6L25", "5L25", "4L25", "4S0", "3L25"],
			payback: ["7M", "6M", "5M", "4M"],
			protect: ["7M", "6M", "5M", "4M", "3M"],
			psybeam: ["7L10", "7L1", "6L1", "5L1", "4L1", "3L22"],
			psychic: ["7M", "6M", "5M", "4M", "3M"],
			raindance: ["7M", "6M", "5M", "4M", "3M"],
			rest: ["7M", "6M", "5M", "4M", "3M"],
			recover: ["7L56"],
			return: ["7M", "6M", "5M", "4M", "3M"],
			rockblast: ["7L1", "6L1", "5L1", "4L1"],
			round: ["7M", "6M", "5M"],
			scald: ["7M", "6M", "5M"],
			secretpower: ["6M", "4M", "3M"],
			seedbomb: ["6T", "5T", "4T"],
			seismictoss: ["3T"],
			signalbeam: ["7L34", "6T", "6L34", "5T", "5L42", "4T", "4L42", "4S0"],
			sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
			sludgebomb: ["7M", "6M", "5M", "4M", "3M"],
			sludgewave: ["7M", "6M", "5M"],
			smackdown: ["7M", "6M", "5M"],
			snore: ["6T", "5T", "4T", "3T"],
			soak: ["7L64", "6L64", "5L61"],
			stringshot: ["4T"],
			substitute: ["7M", "6M", "5M", "4M", "3T"],
			sunnyday: ["7M", "6M", "5M", "4M", "3M"],
			surf: ["7M", "6M", "5M", "4M", "3M"],
			swagger: ["7M", "6M", "5M", "4M", "3T"],
			swift: ["4T", "3T"],
			thief: ["7M", "6M", "5M", "4M", "3M"],
			thunderwave: ["7M", "6M", "5M", "4M", "3T"],
			toxic: ["7M", "6M", "5M", "4M", "3M"],
			waterfall: ["7M", "6M", "5M", "4M", "3M"],
			watergun: ["7L1", "6L1", "5L1", "4L1", "3L1"],
			waterpulse: ["6T", "4M", "3M"],
			whirlpool: ["4M"],
			wringout: ["7L28", "6L28", "5L36", "4L36"],
		},
	},
	spectreon: {
		learnset: {
			workup: ["7M"],
			fakeout: ["7M"],
			dazzlinggleam: ["7M"],
			boomburst: ["7M"],
			shadowball: ["7M"],
			darkpulse: ["7M"],
			hypnosis: ["7M"],
			knockoff: ["7M"],
			shadowclaw: ["7M"],
			frustration: ["7M"],
			reversal: ["7M"],
			suckerpunch: ["7M"],
			willowisp: ["7M"],
			focusblast: ["7M"],
			sacredfire: ["7M"],
			nastyplot: ["7M"],
		},
	},
	hydring: {
		learnset: {
			flashcannon: ["7M"],
			hydropump: ["7L44"],
			magnetbomb: ["7L1"],
			ironhead: ["7L23"],
			thunderbolt: ["7M"],
			grassknot: ["7M"],
			surf: ["7M"],
			waterfall: ["7M"],
			protect: ["7M"],
			scald: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			raindance: ["7M"],
			icebeam: ["7M"],
			blizzard: ["7M"],
			watergun: ["7L1"],
		},
	},
	yinyang: {
		learnset: {
			overheat: ["7M"],
			flamethrower: ["7M"],
			willowisp: ["7M"],
			iciclecrash: ["7M"],
			freezedry: ["7M"],
			icefang: ["7M"],
			auroraveil: ["7M"],
			hypervoice: ["7M"],
			weatherball: ["7M"],
			fakeout: ["7M"],
			naturepower: ["7M"],
			roar: ["7M"],
			encore: ["7M"],
			yawn: ["7M"],
			bugbuzz: ["7M"],
			snarl: ["7M"],
			disarmingvoice: ["7M"],
			shadowball: ["7M"],
			shadowforce: ["7M"],
			hex: ["7M"],
			confuseray: ["7M"],
			razorleaf: ["7M"],
			magicalleaf: ["7M"],
			earthpower: ["7M"],
			clearsmog: ["7M"],
			zenheadbutt: ["7M"],
			powersplit: ["7M"],
			guardsplit: ["7M"],
			powerswap: ["7M"],
			speedswap: ["7M"],
			skillswap: ["7M"],
			metalsound: ["7M"],
			surf: ["7M"],
			aquajet: ["7M"],
		},
	},
	reainein: {
		learnset: {
			bugbite: ["7L2"],
			firepunch: ["7L1"],
			thunderpunch: ["7L1"],
			uturn: ["7M"],
			dragonclaw: ["7M"],
			xscissor: ["7M"],
			protect: ["7M"],
			leechlife: ["7M"],
			dragondance: ["7L32"],
			dracometeor: ["7T"],
			dragonpulse: ["7L22"],
			bugbuzz: ["7L2"],
			hiddenpower: ["7M"],
			return: ["7M"],
			frustration: ["7M"],
			toxic: ["7M"],
			swordsdance: ["7M"],
			bulkup: ["7M"],
			outrage: ["7L55"],
			tackle: ["7L1"],
			substitute: ["7M"],
		},
	},
	bezzoseal: {
		learnset: {
			bugbite: ["7M"],
			spark: ["7M"],
			lunge: ["7M"],
			finalgambit: ["7M"],
			xscissor: ["7M"],
			slash: ["7M"],
			smartstrike: ["7M"],
			sacredsword: ["7M"],
			shadowsneak: ["7M"],
			phantomforce: ["7M"],
			shadowforce: ["7M"],
			uturn: ["7M"],
			sleeptalk: ["7M"],
			metalclaw: ["7M"],
			rocktomb: ["7M"],
			terrordrop: ["7M"],
			iciclespear: ["7M"],
			iceshard: ["7M"],
			bugbuzz: ["7L21"],
			protect: ["7M"],
			substitute: ["7M"],
			hiddenpower: ["7M"],
		},
	},
	cletorcax: {learnset: {
		aerialace: ["7M"],
		attract: ["7M"],
		auroraveil: ["7M"],
		blizzard: ["7M"],
		brickbreak: ["7M"],
		bulldoze: ["7M"],
		calmmind: ["7M"],
		confide: ["7M"],
		defensecurl: ["7L1"],
		doubleteam: ["7M"],
		earthquake: ["7M"],
		facade: ["7M"],
		fling: ["7M"],
		focusblast: ["7M"],
		focuspunch: ["7E"],
		frostbreath: ["7M"],
		frustration: ["7M"],
		gigaimpact: ["7M"],
		gunkshot: ["7L35"],
		gyroball: ["7M"],
		hail: ["7M"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		iceball: ["7L1"],
		icebeam: ["7M"],
		iciclecrash: ["7L1"],
		iciclespear: ["7L1"],
		leechlife: ["7M"],
		metalburst: ["7L1"],
		metalclaw: ["7L1"],
		playrough: ["7L45"],
		poisonjab: ["7M"],
		protect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		sewersmash: ["7L1"],
		shadowclaw: ["7M"],
		slash: ["7L1"],
		sleeptalk: ["7M"],
		sludgebomb: ["7M"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		swordsdance: ["7M"],
		thief: ["7M"],
		thunderbolt: ["7M"],
		toxic: ["7M"],
		workup: ["7M"],
		xscissor: ["7M"],
	}},
	moboreum: {
		learnset: {
			attract: ["7M"],
			brickbreak: ["7M"],
			bulldoze: ["7M"],
			closecombat: ["7L52"],
			confide: ["7M"],
			doubleteam: ["7M"],
			earthquake: ["7M"],
			electroball: ["7L1"],
			facade: ["7M"],
			firepunch: ["7L1"],
			fling: ["7M"],
			focusblast: ["7M"],
			focuspunch: ["7E"],
			frustration: ["7M"],
			gigaimpact: ["7M"],
			gunkshot: ["7L35"],
			knockoff: ["7L24"],
			hiddenpower: ["7M"],
			hyperbeam: ["7M"],
			machpunch: ["7E"],
			playrough: ["7L45"],
			poisonjab: ["7M"],
			protect: ["7M"],
			rest: ["7M"],
			return: ["7M"],
			rockslide: ["7M"],
			round: ["7M"],
			shadowclaw: ["7M"],
			slash: ["7L1"],
			sleeptalk: ["7M"],
			substitute: ["7M"],
			sunnyday: ["7M"],
			swagger: ["7M"],
			swordsdance: ["7M"],
			tackle: ["7L1"],
			thief: ["7M"],
			thunder: ["7M"],
			thunderbolt: ["7M"],
			thunderpunch: ["7L1"],
			thundershock: ["7L1"],
			thunderwave: ["7L1"],
			toxic: ["7M"],
			workup: ["7M"],
			voltswitch: ["7M"],
		},
	},
	minoral: {learnset: {
		amnesia: ["7E", "6E", "5E", "4E", "3E"],
		ancientpower: ["7L17", "6L17", "5L32", "4T", "4L32", "3L45"],
		aquaring: ["7L38", "7E", "6L38", "6E", "5L37", "5E", "4L37", "4E"],
		attract: ["7M", "6M", "5M", "4M", "3M"],
		barrier: ["7E", "6E", "5E", "4E", "3E"],
		bide: ["7E", "6E", "5E"],
		blizzard: ["7M", "6M", "5M", "4M", "3M"],
		bodyslam: ["3T"],
		brine: ["7L27", "6L27", "4M"],
		bubble: ["7L4", "6L4", "5L8", "5D", "4L8", "3L12"],
		bubblebeam: ["7L10", "6L10", "5L25", "4L25", "3L23"],
		bulldoze: ["7M", "6M", "5M"],
		calmmind: ["7M", "6M", "5M", "4M", "3M"],
		camouflage: ["7E", "6E"],
		captivate: ["4M"],
		confide: ["7M", "6M"],
		confuseray: ["7E", "6E", "5E", "5D", "4E", "3E"],
		curse: ["7E", "6E", "5E", "4E"],
		defensecurl: ["3T"],
		dig: ["6M", "5M", "4M", "3M"],
		doubleedge: ["3T"],
		doubleteam: ["7M", "6M", "5M", "4M", "3M"],
		earthpower: ["7L47", "6T", "6L47", "5T", "5L53", "4T", "4L53"],
		earthquake: ["7M", "6M", "5M", "4M", "3M"],
		endeavor: ["6T", "5T", "4T"],
		endure: ["7L35", "6L35", "5L35", "4M", "3T"],
		explosion: ["7M", "6M", "5M", "4M", "3T"],
		facade: ["7M", "6M", "5M", "4M", "3M"],
		flail: ["7L50", "6L50", "5L52"],
		frustration: ["7M", "6M", "5M", "4M", "3M"],
		hail: ["7M", "6M", "5M", "4M", "3M"],
		harden: ["7L1", "6L1", "5L4", "4L4", "3L6"],
		headbutt: ["4T"],
		headsmash: ["7E", "6E", "5E"],
		hiddenpower: ["7M", "6M", "5M", "4M", "3M"],
		icebeam: ["7M", "6M", "5M", "4M", "3M"],
		iciclespear: ["7E", "6E", "5E", "4E", "3E"],
		icywind: ["6T", "5T", "4T"],
		ingrain: ["7E", "6E", "5E", "4E", "3E"],
		irondefense: ["7L29", "6T", "6L29", "5T", "5L29"],
		lightscreen: ["7M", "6M", "5M", "4M", "3M"],
		liquidation: ["7E"],
		luckychant: ["7L23", "6L23", "5L28", "4L28"],
		magiccoat: ["6T", "5T", "4T"],
		mimic: ["3T"],
		mirrorcoat: ["7L45", "6L45", "5L48", "4L48", "3L39"],
		mist: ["7E", "6E", "5E", "4E", "3E"],
		mudslap: ["4T", "3T"],
		mudsport: ["3S0"],
		naturalgift: ["4M"],
		naturepower: ["7M", "7E", "6M", "6E", "5E", "4E"],
		powergem: ["7L41", "6L41", "5L44", "4L44"],
		protect: ["7M", "6M", "5M", "4M", "3M"],
		psychic: ["7M", "6M", "5M", "4M", "3M"],
		raindance: ["7M", "6M", "5M", "4M", "3M"],
		recover: ["7L8", "6L8", "5L13", "4L13", "3L17"],
		reflect: ["7M", "6M", "5M", "4M", "3M"],
		refresh: ["7L13", "6L13", "5L16", "4L16", "3L17"],
		rest: ["7M", "6M", "5M", "4M", "3M"],
		return: ["7M", "6M", "5M", "4M", "3M"],
		rockblast: ["7L31", "6L31", "5L20", "4L20", "3L34"],
		rockpolish: ["7M", "6M", "5M", "4M"],
		rockslide: ["7M", "6M", "5M", "4M", "4E", "3T", "3E"],
		rocksmash: ["6M", "5M", "4M", "3M"],
		rocktomb: ["7M", "6M", "5M", "4M", "3M"],
		rollout: ["4T", "3T"],
		round: ["7M", "6M", "5M"],
		safeguard: ["7M", "6M", "5M", "4M", "3M"],
		sandstorm: ["7M", "6M", "5M", "4M", "3M"],
		scald: ["7M", "6M", "5M"],
		screech: ["7E", "6E", "5E", "4E", "3E"],
		secretpower: ["6M", "4M", "3M"],
		selfdestruct: ["3T"],
		shadowball: ["7M", "6M", "5M", "4M", "3M"],
		sleeptalk: ["7M", "6M", "5T", "4M", "3T"],
		snore: ["6T", "5T", "4T", "3T"],
		spikecannon: ["7L20", "6L20", "5L40", "4L40", "3L28"],
		stealthrock: ["6T", "5T", "5D", "4M"],
		stoneedge: ["7M", "6M", "5M", "4M"],
		strength: ["6M", "5M", "4M", "3M"],
		substitute: ["7M", "6M", "5M", "4M", "3T"],
		suckerpunch: ["4T"],
		sunnyday: ["7M", "6M", "5M", "4M", "3M"],
		surf: ["7M", "6M", "5M", "4M", "3M"],
		swagger: ["7M", "6M", "5M", "4M", "3T"],
		tackle: ["7L1", "6L1", "5L1", "4L1", "3L1", "3S0"],
		toxic: ["7M", "6M", "5M", "4M", "3M"],
		waterpulse: ["7E", "6T", "6E", "5E", "4M", "3M"],
		whirlpool: ["4M"],
	}},
};