'use strict';

exports.BattlePokedex = {
	jirachi: {
		inherit: true,
		types: ["Psychic", "Cosmic"],
	},
	deoxys: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxysattack: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxysdefense: {
		inherit: true,
		types: ["Cosmic"],
	},
	deoxysspeed: {
		inherit: true,
		types: ["Cosmic"],
	},
	metagross: {
		inherit: true,
		types: ["Steel", "Cosmic"],
	},
	lunatone: {
		inherit: true,
		types: ["Psychic", "Cosmic"],
	},
	solrock: {
		inherit: true,
		types: ["Rock", "Cosmic"],
	},
	arceus: {
		inherit: true,
		otherFormes: ["arceusbug", "arceuscosmic", "arceusdark", "arceusdragon", "arceuselectric", "arceusfairy", "arceusfighting", "arceusfire", "arceusflying", "arceusghost", "arceusgrass", "arceusground", "arceusice", "arceuspoison", "arceuspsychic", "arceusrock", "arceussteel", "arceuswater"],
	},
	arceuscosmic: {
		num: 493,
		species: "Arceus-Cosmic",
		baseSpecies: "Arceus",
		forme: "Cosmic",
		formeLetter: "C",
		types: ["Cosmic"],
		gender: "N",
		baseStats: {hp: 120, atk: 120, def: 120, spa: 120, spd: 120, spe: 120},
		abilities: {0: "Multitype"},
		heightm: 3.2,
		weightkg: 320,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	silvally: {
		inherit: true,
		otherFormes: ["silvallybug", "silvallycosmic", "silvallydark", "silvallydragon", "silvallyelectric", "silvallyfairy", "silvallyfighting", "silvallyfire", "silvallyflying", "silvallyghost", "silvallygrass", "silvallyground", "silvallyice", "silvallypoison", "silvallypsychic", "silvallyrock", "silvallysteel", "silvallywater"],
	},
	silvallycosmic: {
		num: 773,
		species: "Silvally-Cosmic",
		baseSpecies: "Silvally",
		forme: "Cosmic",
		formeLetter: "C",
		types: ["Cosmic"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	cosmog: {
		inherit: true,
		types: ["Cosmic"],
	},
	cosmoem: {
		inherit: true,
		types: ["Cosmic"],
	},
	solgaleo: {
		inherit: true,
		types: ["Cosmic", "Steel"],
	},
	lunala: {
		inherit: true,
		types: ["Cosmic", "Ghost"],
	},
	cleffa: {
		inherit: true,
		types: ["Fairy", "Cosmic"],
	},
	clefairy: {
		inherit: true,
		types: ["Fairy", "Cosmic"],
	},
	clefable: {
		inherit: true,
		types: ["Fairy", "Cosmic"],
	},
	elgyem: {
		inherit: true,
		types: ["Cosmic", "Psychic"],
	},
	beheeyem: {
		inherit: true,
		types: ["Cosmic", "Psychic"],
	},
	necrozma: {
		inherit: true,
		types: ["Cosmic"],
	},
	cresselia: {
		inherit: true,
		types: ["Psychic", "Cosmic"],
	},
	golduck: {
		inherit: true,
		types: ["Water", "Psychic"],
	},
	milotic: {
		inherit: true,
		types: ["Water", "Fairy"],
	},
	flygon: {
		inherit: true,
		types: ["Bug", "Dragon"],
	},
	audino: {
		inherit: true,
		types: ["Normal", "Fairy"],
		abilities: {0: "Healer", 1: "Regenerator", H: "Triage"},
	},
	luxray: {
		inherit: true,
		types: ["Electric", "Dark"],
		abilities: {0: "Strong Jaw", 1: "Intimidate", H: "Guts"},
	},
	arbok: {
		inherit: true,
		types: ["Poison", "Dark"],
	},
	seviper: {
		inherit: true,
		types: ["Poison", "Dark"],
	},
	weezing: {
		inherit: true,
		types: ["Poison", "Fire"],
	},
	zangoose: {
		inherit: true,
		types: ["Normal", "Fighting"],
	},
	mismagius: {
		inherit: true,
		types: ["Ghost", "Fairy"],
	},
	sceptile: {
		inherit: true,
		types: ["Grass", "Dragon"],
	},
	electivire: {
		inherit: true,
		types: ["Electric", "Fighting"],
	},
	magmortar: {
		inherit: true,
		types: ["Fire", "Electric"],
		abilities: {0: "Flame Body", 1: "Galvanize", H: "Vital Spirit"},
	},
	bellossom: {
		inherit: true,
		types: ["Grass", "Fairy"],
	},
	ursaring: {
		inherit: true,
		types: ["Normal", "Fighting"],
	},
	sunflora: {
		inherit: true,
		types: ["Grass", "Fire"],
		abilities: {0: "Chlorophyll", 1: "Solar Power", H: "Drought"},
	},
	furret: {
		inherit: true,
		types: ["Normal", "Ghost"],
	},
	feraligatr: {
		inherit: true,
		types: ["Water", "Dragon"],
	},
	dhelmise: {
		inherit: true,
		types: ["Ghost", "Steel"],
	},
	avalugg: {
		inherit: true,
		types: ["Ice", "Steel"],
	},
	cherrim: {
		inherit: true,
		types: ["Grass", "Fire"],
	},
	pachirisu: {
		inherit: true,
		types: ["Electric", "Fairy"],
	},
	florges: {
		inherit: true,
		types: ["Fairy", "Grass"],
	},
	eelektross: {
		inherit: true,
		types: ["Electric", "Bug"],
	},
	chatot: {
		inherit: true,
		abilities: {0: "Keen Eye", 1: "Tangled Feet", H: "Amplifier"},
	},
	beautifly: {
		inherit: true,
		types: ["Bug", "Fairy"],
	},
	galvantula: {
		inherit: true,
		abilities: {0: "Compound Eyes", 1: "Galvanize", H: "Swarm"},
	},
	granbull: {
		inherit: true,
		types: ["Fairy", "Dragon"],
	},
	noctowl: {
		inherit: true,
		types: ["Normal", "Ghost"],
	},
	castform: {
		inherit: true,
		otherFormes: ["castformsunny", "castformrainy", "castformsnowy", "castformsandy", "castformcloudy"],
	},
	castformsandy: {
		num: 351,
		species: "Castform-Sandy",
		baseSpecies: "Castform",
		forme: "Sandy",
		formeLetter: "S",
		types: ["Ground"],
		baseStats: {hp: 70, atk: 70, def: 70, spa: 70, spd: 70, spe: 70},
		abilities: {0: "Forecast"},
		heightm: 0.3,
		weightkg: 0.8,
		color: "Brown",
		eggGroups: ["Fairy", "Amorphous"],
	},
	castformcloudy: {
		num: 351,
		species: "Castform-Cloudy",
		baseSpecies: "Castform",
		forme: "Cloudy",
		formeLetter: "C",
		types: ["Flying"],
		baseStats: {hp: 70, atk: 70, def: 70, spa: 70, spd: 70, spe: 70},
		abilities: {0: "Forecast"},
		heightm: 0.3,
		weightkg: 0.8,
		color: "Blue",
		eggGroups: ["Fairy", "Amorphous"],
	},

	cletorcax: {
		num: -9000,
		species: "Cletorcax",
		types: ["Poison", "Ice"],
		baseStats: {hp: 68, atk: 120, def: 97, spa: 92, spd: 119, spe: 104},
		abilities: {0: "Toxic Triumph", H: "Regenerator"},
		heightm: 4.6,
		weightkg: 120.5,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	smk: {
		num: -9001,
		species: "SMK",
		types: ["Dark", "Ghost"],
		baseStats: {hp: 65, atk: 120, def: 40, spa: 20, spd: 40, spe: 140},
		abilities: {0: "Midlife Crisis", H: "Prankster"},
		heightm: 1.3,
		weightkg: 92,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	musteltank: {
		num: -9002,
		species: "Musteltank",
		types: ["Steel", "Poison"],
		baseStats: {hp: 100, atk: 115, def: 110, spa: 40, spd: 100, spe: 5},
		abilities: {0: "Battle Armor", 1: "Tough Claws", H: "Rust"},
		heightm: 1.8,
		weightkg: 90.7,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	pence: {
		num: -9003,
		species: "Pence",
		types: ["Fairy", "Fighting"],
		baseStats: {hp: 70, atk: 150, def: 70, spa: 150, spd: 70, spe: 45},
		abilities: {0: "Contrary"},
		heightm: 1.8034,
		weightkg: 72,
		color: "White",
		eggGroups: ["Human-like"],
	},
	frioth: {
		num: -9004,
		species: "Frioth",
		types: ["Ice", "Bug"],
		baseStats: {hp: 80, atk: 110, def: 100, spa: 90, spd: 75, spe: 95},
		abilities: {0: "Ice Body", 1: "Snow Cloak", H: "Aerilate"},
		heightm: "0.6096",
		weightkg: "20.63845",
		color: "Blue",
		eggGroups: ["Bug", "Water 3"],
	},
	octillery: {
		inherit: true,
		evos: ["octanko"],
	},
	octanko: {
		num: -9005,
		species: "Octanko",
		types: ["Water", "Steel"],
		baseStats: {hp: 90, atk: 105, def: 125, spa: 110, spd: 85, spe: 40},
		abilities: {0: "Shell Armor", 1: "Sniper", H: "Regenerator"},
		heightm: "103",
		prevo: "octillery",
		weightkg: "532",
		color: "Blue",
		evoLevel: 53,
		eggGroups: ["Water 3"],
	},
	eevee: {
		inherit: true,
		evos: ["vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "spectreon"],
	},
	spectreon: {
		num: -9006,
		species: "Spectreon",
		types: ["Ghost"],
		baseStats: {hp: 75, atk: 110, def: 45, spa: 120, spd: 45, spe: 130},
		abilities: {0: "Vengeful", H: "Hatred"},
		evoLevel: 22,
		heightm: 2,
		weightkg: 0.5,
		prevo: "eevee",
		color: "Purple",
		eggGroups: ["Field", "Amorphous"],
	},
	hydring: {
		num: -9007,
		species: "Hydring",
		types: ["Steel", "Water"],
		baseStats: {hp: 150, atk: 59, def: 101, spa: 70, spd: 95, spe: 50},
		abilities: {0: "Water Bubble", 1: "Swift Swim", H: "Jewel Crack"},
		color: "Gray",
		heightm: 6.8,
		weightkg: 67.2,
		eggGroups: ["Mineral"],
	},
	yinyang: {
		num: -9008,
		species: "Yinyang",
		types: ["Ice", "Fire"],
		baseStats: {hp: 75, atk: 90, def: 93, spa: 110, spd: 93, spe: 109},
		abilities: {0: "Refrigerate", 1: "Drought"},
		color: "Blue",
		heightm: 2.2,
		weightkg: 0.1,
		eggGroups: ["Undiscovered"],
	},
	reainein: {
		num: -9009,
		species: "Reainein",
		types: ["Dragon", "Bug"],
		baseStats: {hp: 78, atk: 130, def: 111, spa: 130, spd: 85, spe: 100},
		abilities: {0: "Tough Claws"},
		color: "Blue",
		heightm: 2.2,
		weightkg: 0.1,
		eggGroups: ["Bug"],
	},
	bezzoseal: {
		num: -9010,
		species: "Bezzoseal",
		types: ["Bug", "Ghost"],
		baseStats: {hp: 83, atk: 101, def: 82, spa: 80, spd: 122, spe: 122},
		abilities: {0: "Compound Eyes", H: "Magic Bounce"},
		color: "Yellow",
		heightm: 1.1,
		weightkg: 2,
		eggGroups: ["Bug"],
	},
	moboreum: {
		num: -9011,
		species: "Moboreum",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 88, atk: 132, def: 87, spa: 101, spd: 85, spe: 92},
		abilities: {0: "Iron Fist", 1: "Technician", H: "Speed Boost"},
		color: "Yellow",
		heightm: 5.7,
		weightkg: 134.6,
		eggGroups: ["Human-like"],
	},
	corsola: {
		inherit: true,
		prevo: "minoral",
	},
	minoral: {
		num: -9012,
		species: "Minoral",
		types: ["Water", "Rock"],
		baseStats: {hp: 45, atk: 45, def: 70, spa: 45, spd: 70, spe: 20},
		abilities: {0: "Hustle", 1: "Natural Cure", H: "Regenerator"},
		heightm: 0.6,
		weightkg: 5,
		color: "Pink",
		evos: ["corsola"],
		eggGroups: ["Water 1", "Water 3"],
	},
};