'use strict';

exports.BattleMovedex = {
	"throw": {
		basePower: 60,
		priority: -1,
		accuracy: true,
		desc: "Forces the foe to swap out.",
		forceSwitch: true,
		category: "Physical",
		pp: 40,
		flags: {protect: 1, mirror: 1, contact: 1},
		num: -600,
		isViable: true,
		secondary: false,
		target: "normal",
		type: "Normal",
		zMovePower: 120,
		contestType: "Tough",
	},
	"basicattack": {
		num: -601,
		accuracy: 100,
		basePower: 60,
		category: "Physical",
		desc: "No additional effect.",
		shortDesc: "No additional effect.",
		id: "basicattack",
		name: "Basic Attack",
		pp: 35,
		priority: 0,
		flags: {contact: 1, protect: 1, mirror: 1},
		secondary: false,
		target: "normal",
		type: "Normal",
		zMovePower: 120,
		contestType: "Tough",
	},
	"superjumppunch": {
		id: "superjumppunch",
		name: "Super Jump Punch",
		basePower: 120,
		accuracy: 90,
		category: "Physical",
		pp: 10,
		flags: {protect: 1, contact: 1, mirror: 1, punch: 1},
		hasCustomRecoil: true,
		onMoveFail: function (target, source, move) {
			this.damage(source.maxhp / 3, source, source, 'superjumpkick');
		},
		isViable: true,
		desc: "If this attack is not successful, the user loses a third of its maximum HP, rounded down, as crash damage. Pokemon with the Ability Magic Guard are unaffected by crash damage.",
		shortDesc: "User is hurt by 33% of its max HP if it misses.",
		secondary: false,
		target: "normal",
		type: "Fighting",
		zMovePower: 195,
		contestType: "Cool",
	},
	"cape": {
		id: "cape",
		name: "Cape",
		category: "Special",
		basePower: 60,
		priority: 1,
		pp: 15,
		flags: {protect: 1, mirror: 1, gravity: 1, distance: 1},
		desc: "No additional effects.",
		secondary: false,
		target: "normal",
		type: "Normal",
		zMovePower: 120,
		contestType: "Cool",
	},
	"fireball": {
		id: "fireball",
		name: "Fireball",
		basePower: 80,
		accuracy: true,
		priority: 0,
		secondary: {
			chance: 10,
			status: "brn",
		},
		pp: 15,
		flags: {protect: 1},
		desc: "30% chance to burn target.",
		target: "normal",
		type: "Fire",
		zMovePower: 150,
		contestType: "Cool",
	},
	"fludd": {
		id: "fludd",
		name: "F.L.U.D.D.",
		basePower: 120,
		accuracy: 95,
		priority: 0,
		secondary: false,
		desc: "No additional effects.",
		pp: 5,
		flags: {protect: 1, mirror: 1},
		target: "normal",
		type: "Normal",
		zMovePower: 180,
		contestType: "Tough",
	},
};